/* Auto-generated by news-fetch.mjs — do not edit by hand. */
window.VT_NEWS = {
  "generatedAt": "2026-06-27T10:00:15.922Z",
  "window": "24–48h",
  "total": 41,
  "last24": 34,
  "sources": 39,
  "categories": [
    {
      "name": "Cybersecurity",
      "count": 13
    },
    {
      "name": "Data Breaches",
      "count": 14
    },
    {
      "name": "Vulnerabilities",
      "count": 14
    }
  ],
  "items": [
    {
      "title": "LastPass suffers another data breach, but this time your password vault is safe",
      "link": "https://news.google.com/rss/articles/CBMingFBVV95cUxNOGdfMlBQWnVWV0VPcmt4bGlXNS1vVXhHNm5vQ3NOUnhQQThTb1BPZmNDQjdfXzVLc1FkNk5PZW5TV3RPQV9yOHlKR0V5OS1PYzhpeWg4dVY2eDU5ZkhjUHQyTVJPRTNnSnk2SGcxQUd2azNRZ2gycG5UVWJKMFVvb01MLXRzMVdpaTVEV28zVzc3Y3dIUUthejl5b0ZmUQ?oc=5",
      "source": "Yahoo Tech",
      "domain": "tech.yahoo.com",
      "published": "2026-06-27T08:11:11.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "Accenture, OpenAI: This Week's Top Five Stories in Cyber",
      "link": "https://news.google.com/rss/articles/CBMifkFVX3lxTE1WTFhvaVE4dGk4SlJJZHlUajJReWxRU3d2RkFsYXk0ZWJab082UVpGWVpUVmw2Nk5PbVhKQ3RvcGlEQVRIZVVWekJ5Z2RaUFJrWnlxcmxqZHUxLWtKSy02dGNzeUxnZG55ZXFCNzdvWjQxX3RmQUs5d3hZQ0xUZw?oc=5",
      "source": "Cyber Magazine",
      "domain": "cybermagazine.com",
      "published": "2026-06-27T08:04:50.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "OpenAI limits its latest ChatGPT product to Trump-approved customers during cybersecurity review",
      "link": "https://news.google.com/rss/articles/CBMitwFBVV95cUxQUGJ0d3BuM2dQcWZOV3BvYjRfN0tNZEM5M0JDVUItc0JNQzR2RUlOeVpkN2JhUEFzLUg0MTVnVS0zZWxSaGlwckRUSUg3SkFVaEdqQ0JRR0tDNDE3Si1YWjd4RXU1Ri1OY1BFMTM5eUp5TmZ3UE9UY3F2bVgtY1dpVl9jc3JmOFNtQk1ETmdJYmk1VTd0dlpab0Z6NEZrTzcxLW1iU2tqNTFGSDlFM1hWNG5ldnVwNGc?oc=5",
      "source": "Pittsburgh Post-Gazette",
      "domain": "post-gazette.com",
      "published": "2026-06-27T06:23:41.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "CCC&TI cybersecurity program gains national distinction",
      "link": "https://news.google.com/rss/articles/CBMi4AFBVV95cUxOOFJLblpJN2VIYnE2NlVPeDZmZDFPS3g2SUJMT2ZZYjI0T0FpRUlvUG5zSUloRjlHY2hOVjlpY1VYaUJVT1hMMUJFTFRHU3NiblF4b2hrcHM1eE1MLWVGVkhPMEFseC1hbDRkeGlYUWZoVXVZZW90Qmk3cTY0T090R2FhVUZNbzZlenVTb2luUHNZaGVIend4Q3dncE5xb1B0MUV5WWxLM2ZUTUx6ZWZPTWpDSWJ1cHRBVi1vekpJdWxrMzRkYnk4Z3hySjc0WF9KNHg2VGtqNEkwWUNHM0Y2bQ?oc=5",
      "source": "thepaper.media",
      "domain": "thepaper.media",
      "published": "2026-06-27T04:15:00.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "Anthropic Gets US Government's Permission To Redeploy Its Mythos Cybersecurity AI Model",
      "link": "https://news.google.com/rss/articles/CBMiigFBVV95cUxOQXVBS09UbmlneU1BLWw0T3NvaUFLOW84NXpocVVLRjVPVVNrdE9rb1FXVmdoemNqak92eFlYY09RcDI2T1RzQWViOWxndzhpdjU1eWVVU1BhUkJOMlFqbkhVaGdrbUVyMmFudnpZRUVBWHMzRzZwUHowNzBsUzAzM0wweWFMZmRsd0E?oc=5",
      "source": "Engadget",
      "domain": "engadget.com",
      "published": "2026-06-27T02:54:00.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "Cybersecurity - Blogs: Can't Tell a Hacker by Their Hat? Color is Critical",
      "link": "https://news.google.com/rss/articles/CBMimAFBVV95cUxQd29lcnVrTVJHUjUtVDZsclRqLXJocE9uVnZhQVkyMVg3ZEhGM3RPVlVOM0FBUUdxOVNieGRCQXVnbzI3dnpqaUNRTUlvVlBRc1BxZVNOdlhuS2NxREs3NFd0d1lvdW1UNHVfRHNpT1F0c2t2MVFQWFpVNVFVLW5pVGVzaFd1ZVdsRVdiZFJyem5tN0YtQ3pFeA?oc=5",
      "source": "IN.gov",
      "domain": "in.gov",
      "published": "2026-06-27T01:44:10.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "Huntsville Hospital vendor hit by data breach: What patients need to do now",
      "link": "https://news.google.com/rss/articles/CBMisAFBVV95cUxQd2hjXzdXclVNNWJlT3dhN0x4bDJybWU0aEViZVdUcmZHZnJaazlsSkx0WDAwcnBQTmJ3N0lNWWpFdW5fNUhDYTAxM21BRGdzLUt2aXdqckMxZjhsam5rUFJ3MFFWU3ViOExEUk9VSDA5R2I4a084U1o2aTZtV19obTA3RmJPb1ZWNHJxMzNabEIya2VBNjM4RzN4RFNYeUsxdVdUY2g3TTM0THp5S0RTSdIBxAFBVV95cUxPYUhMWjFOaFZXUHRKSjVNMnM2T3RGUFdqY2pyUF8xOWZRNXF6V0tMYTVQbzd0RG41RWhsdEJWUmY1N05mU1QwbHpnVGNScjJ0UHBxc0FyUWJrZzRpckFSbHFxTmFpcjhiRE1tNkNPOFNjakpqNV94Y21rcHlPZ3dLc3Y4TEZRcFZMWVRkbFlTZGg3c3hVdVhfbjFRaTZNd2lsQjVyRnQ5X0d1U1VDc2YtVnp4UWQ0am91bTRfTHBtTkl4LXFE?oc=5",
      "source": "AL.com",
      "domain": "al.com",
      "published": "2026-06-27T01:02:00.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "OpenAI and Anthropic limit new AI models to Trump-approved customers during cybersecurity review",
      "link": "https://news.google.com/rss/articles/CBMiqgFBVV95cUxQNmF5MEZucTFsVmZudmVjU0RpalFGZHdteVFrN2dZM1F0elpFYy1xQ0x5elRSVXE3VTdueTZpdFZNdWZybFFqV1pVTkhfVlpBcC03MFZGS2RZQ0ZLNDV3a3Z2eVZVS3Bnc1NBaTJQLTVXZ213YkkzdTd0djVNNkRLclJ2YTFVeU9sUXJ1Y3FLcUVXODhVbTUxOEhtTVNfS1l5cktra0xxWXlqZw?oc=5",
      "source": "AP News",
      "domain": "apnews.com",
      "published": "2026-06-27T00:59:00.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "US government allows Anthropic limited release of AI model that sparked cybersecurity concerns",
      "link": "https://news.google.com/rss/articles/CBMibEFVX3lxTE1lX2FHbTI1SEJfWTJ4WmMyeVdfSHo3V3NDbndfbUdaTFAyRlJtX09WY0pUWkIzTkVpOEhpcmEyY2xPeElZdW04eU9hc2Q2TU1xcDhlUzR4WU1iamN1OXJDQkY2d3NMQ3p5WTRYNg?oc=5",
      "source": "CNN",
      "domain": "cnn.com",
      "published": "2026-06-27T00:22:00.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "Students exposed to challenges, opportunities in at cybersecurity camp",
      "link": "https://news.google.com/rss/articles/CBMisAFBVV95cUxON0Z1QWhOc05DaWUyaWxFM1JteXpRNGszZ0xEMG5WQmZLWGFvNFhPZnFpUlJ6MHI3QnBhLU9DckdqZmJBODF1UUpmTWVKZTYyVWhGblBMVVpWVjV2TWpWaGxLQ2xVVzIyREFMU0FPVFZvcHJXSFJtb3JqRU1MOE5jcmNWaUtqTG91TVBoYlRNclZUalV3WWE1T1p3YmZSUkY0ek1JUG9qZ3NHLXlvTExyVg?oc=5",
      "source": "TribLIVE.com",
      "domain": "triblive.com",
      "published": "2026-06-26T23:34:20.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "Hackers exploit critical PTC Windchill PLM software flaw",
      "link": "https://news.google.com/rss/articles/CBMipgFBVV95cUxOR3k4RklvVFZpX3lNX0NkeHNQYkdDbGVuQWJaMTBNUkZ3Q01oTkdjVTlQUU5aRkxPZngzS3pXeklONnBfeVlNQWxJSUFnYWxpV0VJWWFONWNxRG5rTVhRRzZMZ19hZFBEaXJqcDIxWDFGMV9aNVJLSmZpMy1SNTk2QUN6b1h4TmVabE5HenZMd2RRbVRoMFZDYnBiLTlkX0VJNElLLS1n?oc=5",
      "source": "csoonline.com",
      "domain": "csoonline.com",
      "published": "2026-06-26T23:32:41.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "Sustaining Cybersecurity Gains Becomes the Next Challenge",
      "link": "https://news.google.com/rss/articles/CBMilAFBVV95cUxQcVpZZlFQS3p4Y0taREJLZ2F4MWs4d1AyVlR5OGRYTUhYenRYc0V2dGJjU3pRcXl5Z0J3Y1YwR0dpd1ozQzd1TVRHcFU2dHhuUXUtblpXYm5GelpHY243RC0yOE9CNTFNSW90Nkh3OGFwUnFrNG1EU1VGRGhEbHRNcElqRzE0bjdROUx1bFFXZl9GOXFF?oc=5",
      "source": "govtech.com",
      "domain": "govtech.com",
      "published": "2026-06-26T22:05:57.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "AI is a cybersecurity problem — and also, a solution",
      "link": "https://news.google.com/rss/articles/CBMimwFBVV95cUxPaXR5NTYwY1F4OFpzN0F0VHhITTVvNGFtSy1UaUthUDdqSU81T3pmczEybGl4X0d3cllIbmVZel9lN1FZZWZoNkdES2NkNjY3b3FaR0g5MWRDbElGUXdGaTFfNU9kVW04SHNSNG5RZ0pHRHdEeVNMTUVQLV96Mjh6SWdLcnNWQmhPUEZNaUtQNEVyb0ozdS1jVEt1OA?oc=5",
      "source": "ASU News",
      "domain": "news.asu.edu",
      "published": "2026-06-26T21:41:37.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "Amazon Q Developer extension vulnerability could have exposed cloud credentials | brief | SC Media",
      "link": "https://news.google.com/rss/articles/CBMipgFBVV95cUxPaHM4MjRSRlVNNkhLS3UyaGdrX3AyazR3N05lZHpvS0FPUVRiM21hdHd6ekZseUh6Q191dlZXS0ZOT1VlaG14aFk3dkF0Ylk4UmM4dlNtQ3V1U3ZhMUlrZ3NWeGVwWXlFVWM5bUFldGVjenFuSXFVdWFfSlk3V2RuLUNhOHR5a1g4TlVVTk5SMlliaFl3VV91a20zSjB0UktTN3RROTZR?oc=5",
      "source": "SC Media",
      "domain": "scworld.com",
      "published": "2026-06-26T21:33:41.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "Challenge Manufacturing Company Data Breach Lawsuit Investigation",
      "link": "https://news.google.com/rss/articles/CBMilAFBVV95cUxQVEJrRG1PRE9tRzBGZFVpb1J1WE1ycDlqNmNVRm1mMGxGdUxPRkgzR2JLUlktSzAwNFZtWlJLTmhXUlQxS3A4RE9rb3NIUFdLS3BfMUlrZDB4MVNMcEIza3ljbWRDSnRGaVpXUkd1Wl9TRUdZYVJMbGU2QkZnTS1jU2VZbHJaM3l4cXFCb09UMFFtazNT?oc=5",
      "source": "Claim Depot",
      "domain": "claimdepot.com",
      "published": "2026-06-26T21:06:47.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "Nissan North America Data Breach Reported, Lawsuit Possible",
      "link": "https://news.google.com/rss/articles/CBMihgFBVV95cUxOVW14UWl2RGpxSFpRcmt2X0NPOTNQWHAyVzFrSzR2R1BGX2pMRi1zTmdmN1V3Q3lzeXAyenZrV0VibnBoUjhOWlRqQlZDWmZLUHZYZFZXandScnduVFdpcTVHbmZlQVNTOG9BVGNxeXItM0s2YzZIN2NUaTNMdmF2VXp1SEE2QQ?oc=5",
      "source": "ClassAction.org",
      "domain": "classaction.org",
      "published": "2026-06-26T21:00:13.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "Huntsville Hospital patients’ data exposed in third-party security breach",
      "link": "https://news.google.com/rss/articles/CBMipAFBVV95cUxNNHdJdm1IS2dfRjVXVjctb2NkMVQxTjhwSG1ENUg4ZHdKU1dMa3diOF9mN0VMWjVxWmtLNUpEOUlONVhFR0d5LTFFUWl0ZGw0QmdiUFI0OS0wRlcxMFowQmdNWWxZVFg4c0s2bEtFalp2UTQwYXBIMmEtclpITlRuX3U0TzBJTHpzNUd0R1FSYVFFd0VaZWtWZEtGbFZBXzZhR0hVX9IBuAFBVV95cUxOdDBLc2VndTRsX1owOG1GMGx5Qmw5dm9TYWRhazQ1bFFzRXl6ckRUYXlRcFo0RXZEd2NkYW1ySmh0c2laSkhGVk9XSXhmQlMyUEc3UDQzSUVUeENiZVNobFdGNW9KTDRTUkJOa00zVUpXbmpIellIdDNKT3EzMXF2SWtraGNYaUFXN0MtNzZiWlE0UUx2TGU2MEg0RWZyMkctUkJiYVEwLXppdmF4cTkzUU1vQ2ZidXd2?oc=5",
      "source": "WAFF",
      "domain": "waff.com",
      "published": "2026-06-26T20:16:00.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "Congress Can Strengthen State and Local Cybersecurity in One Bill | Blogs | Jun 26, 2026",
      "link": "https://news.google.com/rss/articles/CBMiqwFBVV95cUxNRnlKbGNuSTZUbkROM3phcDJ4aHZ5WV9EampTUXdKS2hqc21JZmVGa3VXNkswNkFRU2RpaTZJM2tvTE82X3VGdkhYeDdXRXFNS182T01BZE5CdVdpcEEwX2Mxb2lBQXZoRkZuSVJGdk5yZHZhMGxkcWt1clgxLXlrNWhibHpDM3pIZEw4dTJ1dUtuUWU3bFlJX0RTRkNwOTlfZ1M1bVMtUFE0MHc?oc=5",
      "source": "Information Technology and Innovation Foundation (ITIF)",
      "domain": "itif.org",
      "published": "2026-06-26T20:05:02.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "Alamo Heights ISD Data Breach Affected Nearly 30K",
      "link": "https://news.google.com/rss/articles/CBMikgFBVV95cUxON3FCSXpOOGNMd1R0R3VQb3dRcVBfWGgtdk5XdXkzWlBrRVg3TW00X2ZiSzJRVUVVaFktWGU4SlRmZG5GNEFTcE82M0N6QzdXa2V2aFB3SklPZndUSHl6bURESEduRFgyVzByaHpTMk9SbHRrTFJHVE11X2lwRU1WeHBvVTg1eDBnNHpzQVhvcjQwUQ?oc=5",
      "source": "insider.govtech.com",
      "domain": "insider.govtech.com",
      "published": "2026-06-26T19:57:10.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "CISA sets urgent deadline to fix Cisco flaw exploited in attacks",
      "link": "https://news.google.com/rss/articles/CBMitwFBVV95cUxOQmhlM1F6R1BsTEV1YkZZQzJKbE9BdF8tYXAtSXZaSjl2R0JENWpoTHFvUk5kcVBOVm05aFFrWDRKdng0STYxUWJ3TWR0ZTJhdzBZZHVBT2dfSkZoVGNhOWVYcnRoSlNsT3o1NThhSnhlWVlHZ1c0YnExZnk2M3EzdXI5eDFNWW9RM3VCTUoxNWpsY25pMlFrZHBLVFlQNHB6amFISXplQ1Zla2JCMG9sRDJSQWc2aXPSAbcBQVVfeXFMTkJoZTNRekdQbExFdWJGWUMySmxPQXRfLWFwLUl2Wko5dkdCRDVqaExxb1JOZHFQTlZtOWhRa1g0SnZ4NEk2MVFid01kdGUyYXcwWWR1QU9nX0pGaFRjYTllWHJ0aEpTbE96NTU4YUp4ZVlZR2dXNGJxMWZ5NjNxM3VyOXgxTVlvUTN1Qk1KMTVqbGNuaTJRa2RwS1RZUDRwemphSEl6ZUNWZWtiQjBvbEQyUkFnNmlz?oc=5",
      "source": "BleepingComputer",
      "domain": "bleepingcomputer.com",
      "published": "2026-06-26T19:43:06.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "River Bank & Trust Data Breach Reported; Lawyers Investigating",
      "link": "https://news.google.com/rss/articles/CBMihgFBVV95cUxNZHZQOWJSSXZaTFNiTnljZXJmWU55M0ZjYVh2OV9IUmVfa0poYVoyS1ktOVNKMkphNTBucVpSLUFUQmtOejdpb3pFVTZSME8yYXZrUU1lNUlXUWhNdzBNQzhlbVVMMmlIZUxmOHZqOVNLcXZiVjdFR3k2NUxYT0lmYTU4a3p4UQ?oc=5",
      "source": "ClassAction.org",
      "domain": "classaction.org",
      "published": "2026-06-26T19:17:10.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "What CISOs Need to Know About AI-Driven Vulnerability Prioritization Tools",
      "link": "https://news.google.com/rss/articles/CBMiswFBVV95cUxPaHRQanZzSlRDYXZLSlZkWTk2ZDBsNXlvMlQ1MmdzVE5KUzl2MkpDYTlMVkhlbnQ2ZHRQX0hNTHh5ajlCTGUxWC1iaFVnZWI5VTBSTURUUTJNazl3T3ZqNDVZdldpVDI4X0tjQkx6MWExSms1N3RyaUpmZmNONnpXRlA3a18xbWZhS0d5MHI3bWpCTWxDQ3k0WnNxX3diUFZYcHl0UzJIMmc4OEJvN1I3V0NaZw?oc=5",
      "source": "Security Boulevard",
      "domain": "securityboulevard.com",
      "published": "2026-06-26T19:11:03.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "Phone service restored at ETHS following cybersecurity attack",
      "link": "https://news.google.com/rss/articles/CBMihAFBVV95cUxOUjhzeE93NjRWUFpwanZiV0dxMFFmdzVEcmpLVnZWM1hUaF95dlY2WGF6QmhvSEVBdmRIR3o2d0R5cW43cDRodWFSOVVBenhwdm54TDVmek1icnF2Unh5LUotdWp5VW02ZWtLQWNVZndlZUpKMnBST2ZOVk4xZEE0MUtWbmM?oc=5",
      "source": "Evanston RoundTable",
      "domain": "evanstonroundtable.com",
      "published": "2026-06-26T17:27:24.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "Security Leaders Discuss Texas Hunting, Fishing License Data Breach",
      "link": "https://news.google.com/rss/articles/CBMitgFBVV95cUxPcFJEbGFvLWxqN3hNbnUzMzNuWjcxZ2xGVjBzUGRzaDBiNTF1TEJXV20yQVEwQWpvNkJ3WE4xb2QweUVrdnVJdXZtcDBFSjJ6NWlCM3NEaHRBbGdiSUxNekR5Q0NOb2F0Q1Rrd3NqdWptMFBBcnd3Ym1OMDQ4anhqVTQtcGladUZPbVZTdkNaUk1sbU9Cb21HYUE0NmN5T2UxbGpac0ZvZThNa3FkdzRXcDdZOWw1UQ?oc=5",
      "source": "Security Magazine",
      "domain": "securitymagazine.com",
      "published": "2026-06-26T15:30:00.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "Amazon Q Flaw Enabled Cloud Credential Theft via Malicious Repositories",
      "link": "https://news.google.com/rss/articles/CBMiqAFBVV95cUxOTEN6R19wX25sLXVHNGdTSEVsTzZwV1JseHljaS1DNlRHTGFJTVBFWmNhdlc0VG1CU0V4aXVtb3prTkVnazFvOF94di1SYzNjQWNiUXVmbmlQcmoyRWpzX3c3YzNuWUdHaFdMb2ZycURPLWMyX3pSbEh0QVRENFRaeDd2RWRYQzZHWVZ6RXBlak1Lcl96aXNGTHIyN05MQXVRTmhQS0RkdGjSAagBQVVfeXFMTkxDekdfcF9ubC11RzRnU0hFbE82cFdSbHh5Y2ktQzZUR0xhSU1QRVpjYXZXNFRtQlNFeGl1bW96a05FZ2sxbzhfeHYtUmMzY0FjYlF1Zm5pUHJqMkVqc193N2MzbllHR2hXTG9mcnFETy1jMl96UmxIdEFURDRUWng3dkVkWEM2R1lWekVwZWpNS3JfemlzRkxyMjdOTEF1UU5oUEtEZHRo?oc=5",
      "source": "SecurityWeek",
      "domain": "securityweek.com",
      "published": "2026-06-26T15:25:23.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "Stark-based Northeast Professional Caregivers announces data breach",
      "link": "https://news.google.com/rss/articles/CBMivwFBVV95cUxQbHRDXzRYZ0pmUmhRTkI0QXkxZ2gxZHlrZ2I2NS1Lc1ZGY0JReFN5NmRQQ18yMXN6XzdhaF90YlprVU5uMjJaUTZkcGp4TkRBb1E3Q0FEWEJQUndkYTlHVWh1X0NvdXJ4LVktcWd0ZXNGdkt1MmpKaTZ2eTNJUFN2VnRKU2VhcE9kMDBwZGZSS05kelh3emhxWm5relZSb0FtNS1JMENiRmJ3MHlHUXoxMVk0dmY0Ujc1bE5zbDlOdw?oc=5",
      "source": "Canton Repository",
      "domain": "cantonrep.com",
      "published": "2026-06-26T15:16:00.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "More Klue Breach Victims Identified as Hackers Get Hacked",
      "link": "https://news.google.com/rss/articles/CBMikAFBVV95cUxQWlNpOU1OeVpVemRiR0NzeWk0N0VHNUFXWHdMblg5SVIzdlZsN3pHTnlySF9zWDRJRlBRMlY0b0xDamRmMVFRZUt1UnFka0l1dzM0YjZXM1RzNmJLaFl6cTRCd295b2R3cUp4RXg1b01wTWZOWnFPS1F1T0pUTUFFMWRMWGZ0alQ0R2N1ZWQ5UmjSAZYBQVVfeXFMT2VrQzRvUXp1YUxueTRmNWpqOHNzWXMtTmZBQjE0R3h5bktWcU5XNVlsU0VRMTFDVnR1RmtpRFZpQWd5X3E4R2taa1FCMXVnOEt2U01mdEtvNWJubUVacTl4VUU3Y0ZfejhvTnYzb1FGSTFzNzZMaHBvUDJCalYxSEN5d1dxSmwyM0RabjBObzFuT2E0M3BB?oc=5",
      "source": "SecurityWeek",
      "domain": "securityweek.com",
      "published": "2026-06-26T15:01:33.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "Less than one in ten of cybersecurity pros trust AI testing tools to find vulnerabilities, with over three-quarters say their AI vulnerability scanning tools missed critical flaws",
      "link": "https://news.google.com/rss/articles/CBMivgJBVV95cUxQVW1nZnpWZ08tdHhwRi1RMU10N1VGR1lhWFh3U19pT0ZVYVB3VVVjY2tWLW5ZZjY5cnRDZDh2ellTY2pTLXByRlZ3MERPeFc3QmdHQU9rdV9WcGppSnJSMThCd21jZnA5SGpnS2puZmk1N1VSY3I1N3RpYjk0WDd2Q3ZWZFZaakwtYTVqS2RCT09HaUtjb0FLNGlTVHl4YUtWM2pPNlZKSEU3NG82QUhYcDNwZkNDaUlkeWFMZFZBNjBYeTBMSmtFVk9wWTN6UE5GZnhyblJmWmktRDNXb0k5VEdZRE1PMWpObnEtRDE5bl9GSVU4M0hEUE1UQnh6Zll5UXZjb1FXcFlJTWZNcll6ZVBJMjV2VXVpanE5aVl0VTFEUWVfNHFOLTVwb1puNjdyb0pQVUtQejNORUV3VkE?oc=5",
      "source": "TechRadar",
      "domain": "techradar.com",
      "published": "2026-06-26T14:30:00.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "Is cybersecurity just coding? Myths vs. reality",
      "link": "https://news.google.com/rss/articles/CBMilgFBVV95cUxQbnpqWTZqeGJMLThwZG81Q2tDZURmVUhpb0s3b2ZyOWgtWVd1Q2N3QjhtclhkMU90QTJwb0JFQ3hPdS1KRXp6NTFEdUJGemYtRm1SU3YxV29wS1JrNGwwYlpzTmgtdEFiSjJyS2dDVXZNTGIyeWN4bm8xR2tXYXRMRzZJYWxOU19MMl8zc1ljY25wbFF0WEE?oc=5",
      "source": "Boise State University",
      "domain": "boisestate.edu",
      "published": "2026-06-26T14:00:00.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "Okanogan Behavioral Healthcare Settles Class Action Data Breach Lawsuit",
      "link": "https://news.google.com/rss/articles/CBMilgFBVV95cUxQU21EZ3p1ejlKeGk5OWd5UEZxTzBZZmFoUzY4REt2VzExYTMzZnczWWc2bkJ4Q21WR2xPa3ozVUUyTWNGN3ZvcGU0UlFqUUVQX1A5TEtnSFdSVzh2YWo0R0ZSZ0JHOU1BTnczVS1nZUE2RWRlU2RvTjhxd09HeWdxbVN5NUZkaFhQbDZNWlJka3h4MXpmaWc?oc=5",
      "source": "The HIPAA Journal",
      "domain": "hipaajournal.com",
      "published": "2026-06-26T12:12:42.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "MCP Auto-Execution: From Git Clone to Cloud Compromise in Amazon Q VS Code Extension",
      "link": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE9SMnY3X1VtaTFaZ3ZJQzdnaHU1ejN5TVUzTy1Ya0RlN25vVmJERUppa2Z3bzdXbEZuSVg3VkRMcFdxdVhVZk5wYk8zSlNkZEd4LS1oeGw0dFRXZw?oc=5",
      "source": "wiz.io",
      "domain": "wiz.io",
      "published": "2026-06-26T12:00:01.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "Critical open-source projects get a new security framework",
      "link": "https://news.google.com/rss/articles/CBMiigFBVV95cUxNT2d1b1JhYThNWDJXLTNjTVBETDdPR3gyTVFzRUlKVkhGUURPOHJuYmdhMWcyWjR1UVljZ2NlTm9WdHkyNGJtTE1iVVIyZWsxSUNPMlROWlFLeDZYUnRiSTlobkU1dm93NXpSWFBKcWRyWTByS3MwaldHVlZQTnpWVDZvTVoxLUVyUFE?oc=5",
      "source": "Help Net Security",
      "domain": "helpnetsecurity.com",
      "published": "2026-06-26T11:41:43.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "EXCLUSIVE: Apple supplier Tata tightens internal controls after data breach, sources say",
      "link": "https://news.google.com/rss/articles/CBMi0AFBVV95cUxQX1FQTmEzckxCOXdoVGVNUFVuLW40Zml1ejZZZFFobmsydHFsQy1DNG5EeC1xNThHanpOR1dLV0pKaGtjZ0dhcDdicGFZTzZRLWt3dnJLVWJhZjc0a01LZm1aanQ0NVVvY1RXcG1OOWJ0N1c0bDdSMUR1S1p4TWU3T3ZxYVluZUVBSzRKaE11QmVhQnN5Qm52VVRZYTdVc2h4ZVhIczVlUmdYaWtyREZVT1owYmgxc2ljeER3ZnNOR3NIUDRVbU1aSzFOZ0NDeVFG?oc=5",
      "source": "Reuters",
      "domain": "reuters.com",
      "published": "2026-06-26T10:50:09.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "Azul Addresses the Java Runtime Security Blind Spot Autonomous AI Can Now Exploit",
      "link": "https://news.google.com/rss/articles/CBMixAFBVV95cUxPcVdLLVI3cUNuOXpjU0o0T25fUFRmTFVicjZQY0F3QUd3b29yTDZfNE9YcXIxbnZUM1d6SkNqU0dCZ2VhSS1HbVB2U3NWRDViOHJ3eXRrak96MFJRQzZfWktWMHVSbWp2bGhqOXNNUkRyOERMbllRUEYwZVlsRGRjaGc2bE5va3pJdzVsdFA2Y3ozNWtJeDBlVUxKV0d2V0x5Z0lOV2w1ZW4zTjBKUm9iU0p3UTZkaXg0NTlGdWVpclR2N05a?oc=5",
      "source": "AiThority",
      "domain": "aithority.com",
      "published": "2026-06-26T10:13:17.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "26K+ people impacted by data breach at Alamo Heights ISD, Texas attorney general says",
      "link": "https://news.google.com/rss/articles/CBMirwFBVV95cUxNOHlwekltMWMxRnlqZmZQSjJyNmc2SG41Rzh3UDJsUUxJM0dGV00wYWxPTUUzckRXeUlFdnZxM0FBdmNBZ3oyZ0lINTU5TzBJa05CcHZjWFh4N1dvSTVGdWt1ODF3QU9lQ3pBam5xZzBQNnlLNWJjZ1NySDRESnhxWHhIaTNiUHRVYloyWG83YlJldkNxUlQ1T3o5RDRFN2lnQXV1MGlIdDdMVWdxWHlr?oc=5",
      "source": "KSAT",
      "domain": "ksat.com",
      "published": "2026-06-26T03:19:53.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "Protecting customers faster: How Adobe is responding to AI-accelerated vulnerability discovery",
      "link": "https://news.google.com/rss/articles/CBMiwwFBVV95cUxQeXVjQXhKUlltamtUYVFFRTVONW13amhkU3Jyc0oza0VpTkpvdUt2cnFsV0VzOXAySGg0Ujh3UUJZRElqMmFwb2ZjV2dVUEE1My1lWWNNaHh3SUgwQUZnWlNPUGFRM1hBcm1FWk94d0tEdUc5cmI3Z1BxRl83WXJFR196YUtoRXNoWXpubzBOOUU1cG90Z0dpcFc2RHNOcHIwUkZRWjFaY2Y4UHBtdkRhb2dhSGdtakdVZThjM0Z5R2Y4SGM?oc=5",
      "source": "Adobe",
      "domain": "blog.adobe.com",
      "published": "2026-06-25T19:08:16.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "$10.5M Lemonade Insurance data breach class action settlement",
      "link": "https://news.google.com/rss/articles/CBMizwFBVV95cUxQQU1yRERRcnZWWnBRUUcxVGl5UmJjOGViR2tXcVVNZTI5d2tnRl9mWVFOeUdPc0NsWjdzbHhsM0NfTjRaVFJnbFJnSEFLZU1xcnNrWGl2dVdCUFphUjluLUVac01UZjQxdVpBbkgyU19QWmkxNkJaS3lFeTR2XzN6NVZiUjE1RFF6SENXN3FuM3lwZlpNZFItMTFTbVRLQmxUSEk5RnRsbzRWVFBCRWxBYWlacUlKM0UwMTFQT2NiMy1adzc1WXBPSUpCOUpBcVE?oc=5",
      "source": "Class Action Lawsuits",
      "domain": "topclassactions.com",
      "published": "2026-06-25T17:04:08.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "NVD in the AI Era: The Case for Multi-Source Vulnerability Intelligence",
      "link": "https://news.google.com/rss/articles/CBMic0FVX3lxTE1EdEYyR0FMM0tacXRfTUo5VGZaQzJHdVd6NWRlaDFxT3pQbkVudTVNU1U1ZXF6VU5aMU9ZRVVTU3NzSWprbkYwNUxDdnAzQklGdmxzdmY4aDEzVVI1UUxsbkJoVVZpbzE1UTBnNHI4bXp2SGM?oc=5",
      "source": "Snyk",
      "domain": "snyk.io",
      "published": "2026-06-25T16:49:46.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "2025 Comprehensive Food Security and Vulnerability Analysis in Lao PDR",
      "link": "https://news.google.com/rss/articles/CBMiogFBVV95cUxOOFFRLVBnLThHbFI3NjI2NlY5V29RaG9EeHVpRW1STUhJUGJLQk1VT1Voc0RfWDlscXE1SS1aNThtN2QtM0ctNWZFMkVMTHYtaldGOFNsaWpXMFBwS3hqQ1BkX0thWlNTUkE2dFVJMWI0WmQ0MEc2SDFpNGJfMDhqS0dtUXRWcnVmS2Rra3J6VEJENDZuT0ZqUTZzaFNYR1MzV2c?oc=5",
      "source": "UN World Food Programme",
      "domain": "wfp.org",
      "published": "2026-06-25T12:00:00.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "Update Chrome to patch critical browser security flaws",
      "link": "https://news.google.com/rss/articles/CBMiowFBVV95cUxQWF9RbzlNczlrMUllOHVLeFhTZ2hyd0piWTNtOVY1bUtBajlzQWxSUWxKNHBLZUdNY1JMdjlhOVljTWd6V295aklKWlhUZUVDWmxEV05HQmY3Tm44ZDFjZk5rdzcwcGpxbHVTckNMZlRvc0QtQzBhOVVfaG9yM1RvOGVYTjAzYWpPY0kwWDQ2d0VxVUR3NkJack53U2VMZkFTUzlZ?oc=5",
      "source": "Malwarebytes",
      "domain": "malwarebytes.com",
      "published": "2026-06-25T11:22:55.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "Experts on Experts: Why AI and Compliance Are Forcing A New Security Operating Model",
      "link": "https://news.google.com/rss/articles/CBMiqgFBVV95cUxOVzV2RkI4dnJReGlRbmNYYlFvSGMxMnZUdUU1WDIycWZpeWVxb0xLdmdnVWs2WmdXS3pMREhBb3Q5VnZvU2JKVHpmbllfMjB1RmMzYi1ncUp0QXR1bUw4ZnBUWHp1TEZQVFAxaVRsX1I1MWIxVnRWR3JYSVFXSm5jaER6UWg0NXJQdkV2NGcyakxvSG5CMXdHNGhkUE94MWE4XzBpVDExVDRMZw?oc=5",
      "source": "Rapid7",
      "domain": "rapid7.com",
      "published": "2026-06-25T10:19:04.000Z",
      "category": "Vulnerabilities"
    }
  ]
};
