/* Auto-generated by news-fetch.mjs — do not edit by hand. */
window.VT_NEWS = {
  "generatedAt": "2026-07-29T10:00:10.439Z",
  "window": "24–48h",
  "total": 72,
  "last24": 67,
  "sources": 66,
  "categories": [
    {
      "name": "Cybersecurity",
      "count": 14
    },
    {
      "name": "Data Breaches",
      "count": 14
    },
    {
      "name": "Vulnerabilities",
      "count": 11
    },
    {
      "name": "Ransomware",
      "count": 9
    },
    {
      "name": "Cloud & Infrastructure",
      "count": 11
    },
    {
      "name": "AI & Enterprise Tech",
      "count": 13
    }
  ],
  "items": [
    {
      "title": "Snowflake Cortex AI gateway aims to keep AI agents in check",
      "link": "https://news.google.com/rss/articles/CBMiqgFBVV95cUxOckJNdmlsNVRvdGZEZzRBaWNOYTluNlZBSEJ2NmQ4N1E2emFDNlE1SmZ5RVQwb3o5dTQ3bUJNR1FVMUVrLUlDOGJGUmNiWXE5aG50aXFHMzZVeV83dUpoWFBlWWo4Y0RyZlVDZDBLSVc2bnV4bjhGLUdnNUs0LWJxUi1zZlAzaDd0NVk5VGdkS2ZtMWpsYTNzYlZRTFZqVl9xNHl2VTdjdFlrUQ?oc=5",
      "source": "Techzine Global",
      "domain": "techzine.eu",
      "published": "2026-07-29T08:45:21.000Z",
      "category": "AI & Enterprise Tech"
    },
    {
      "title": "SonicWall warns OT/IT convergence expanding manufacturing cybersecurity risks despite fewer detected attacks",
      "link": "https://news.google.com/rss/articles/CBMi5AFBVV95cUxNQ3U0dFNZYVZ5T3F6TWdfeVVXVWQ5VlktcmtHSlRmOENWWVdRZjQ0SXZkX2NwSVVZQXhOT0RnSi1MZEZIQUVVSFNJcklhcEF6Mlh4RVNXU3BrZUhkZzNJSUJ0bjBSSVVQM18zdDVmNGNOQkN4UnNMWEJLQks4R1kzWWpsM3hHYjBMWDkwSWd6M25XRlNjMlBrMnhBb0JRZGQzTDdjR0k2dWxqZDlYMlB3Mi04WEgyUnBvRGpZakRKNEhhRWhsd2VrVHktSlVBUUszenJmQ2dPc1ZzcG1TUG1aak1BMDU?oc=5",
      "source": "Industrial Cyber",
      "domain": "industrialcyber.co",
      "published": "2026-07-29T08:39:16.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "Root Evidence puts real-world evidence at the center of vulnerability prioritization",
      "link": "https://news.google.com/rss/articles/CBMixwFBVV95cUxPcXdTQ01SU01NalJTM1lGY3RzSlRpMHJUSWJDUE5MX0ozbFZUeGtHNGRqNEZwRzBOUWhMOHAwcUJEakVZNjFzQVdvdVVsd052ZGFyZ1RkNk5yTlh0Vm9kMEdOYW9fOThyS1JWb3J4Nm9HeFJnU2c5Wm9jaDhNYjloRGx1MVBGVjNHRUxQZDVCRXlyWHVsT1U5b0tZVU5VMjdQMUZtX21xZjRNNXVpS2hCaWl1RTRIQU1WaDU0Zm56eFpDMkFhNTNr?oc=5",
      "source": "Help Net Security",
      "domain": "helpnetsecurity.com",
      "published": "2026-07-29T08:07:51.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "Critical Gitea Vulnerability Allows Attackers to Execute Malicious Code Remotely",
      "link": "https://news.google.com/rss/articles/CBMiakFVX3lxTE80VmhrT29wQ0N6MGc2VV80elRfNFJSNDRydEpBcXZwam9OYU5fMF83S2szdndlRXdpei1mSWpLcU9YS3Y0UEdFRUZ6cWt6elZSOTJxQzZYZzNNeGdjMmVpVnVfYWRwbGtyMGfSAWpBVV95cUxPNFZoa09vcENDejBnNlVfNHpUXzRSUjQ0cnRKQXF2cGpvTmFOXzBfN0trM3Z3ZUV3aXotZklqS3FPWEt2NFBHRUVGenFrenpWUjkycUM2WGczTXhnYzJlaVZ1X2FkcGxrcjBn?oc=5",
      "source": "CyberSecurityNews",
      "domain": "cybersecuritynews.com",
      "published": "2026-07-29T08:03:46.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "Inverter supply chains and cybersecurity – Analysis",
      "link": "https://news.google.com/rss/articles/CBMifkFVX3lxTE9oR1VkVHpkUjJGMjBoM25ISnJncGh2T0tQYktFc2wwRzV3amFfWVIyWWY5QW5tZnBRTTF1ZVhkTENhWVBDNWdpUlMwSzN6MTBTa1dDRXh2b1R1d2NLR3M1bkUzeXhhZ2hqRWw3ejgyUGd4alZnLW5CNWFUSHVuQQ?oc=5",
      "source": "IEA – International Energy Agency",
      "domain": "iea.org",
      "published": "2026-07-29T08:00:00.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "GAO: Federal Cybersecurity Rules Create Potentially Duplicative Reporting Requirements Across Critical Sectors",
      "link": "https://news.google.com/rss/articles/CBMi7wFBVV95cUxONTJtOUZ2OTJkUEV4OGtqcVBTTkR3dldJYjI3WjRsbVc4dDBTRkFraDRpdnhzUUhmaGU4MWFTR1UyNXRiSzhFUmlPUWdYZDh3d3NLdm4xaHRYTWtYZGdXMlljSG5oVmJZOFBMcE00VFhPWC1ZbHlwSDFaamVvR3FELTVfNmIzNzE3Z1B3UVh5WHV3N3NMWkZxQXhsazR5MFV4Z29YS0puSl9DRnE1aVVaMXEzSVN1bnp5bHR0U0xCd1dBQzc1UGZBVFdraTZjZmYtVWZral9yMzF4V2FWbW1PUVBtZ296XzlyU2V1dmM5SQ?oc=5",
      "source": "Homeland Security Today",
      "domain": "hstoday.us",
      "published": "2026-07-29T07:34:08.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "Tines introduces AI-native platform for secure enterprise workflow automation",
      "link": "https://news.google.com/rss/articles/CBMivgFBVV95cUxQc3AxblRlbC1ZbDBNYkswUXBEemN3S1dsLUQ2QjdGSlB0emE3clRYVERudG1hX3AyWmFfZnVlUFJXLW1CRXk5TlgxVVdENXkycElWcUFfSTJTRS1kRUdiQVp3Ymk2UEtzdlM4TmhoN0pvSS1YYUZxZUY3dERFdFM3NlN5WjZwVHZXZDZsNzA1V1V4SDgwd2k3SFFEdVZWSHVoNmdhS3FXczNfM2RjWE50WXRkVFB4Zk1FUkxScTVR?oc=5",
      "source": "Help Net Security",
      "domain": "helpnetsecurity.com",
      "published": "2026-07-29T07:33:31.000Z",
      "category": "AI & Enterprise Tech"
    },
    {
      "title": "Ransomware report: VPNs in the crosshairs, AI attacks",
      "link": "https://news.google.com/rss/articles/CBMinwFBVV95cUxPWTZobEFzU0FQLWk0LW53amlxbF9uc21jS2c4dklHRTBGUDI1YnQ2ZS01RUk4UUJGV0VTdUNGOHpmTmo4Nm9xcmJJN1FFdzQ0ek1mWVNTMm9iOFpuckNRVktYeEJTbUxKMk52bmtULWtzQVNyT0c0YWUzWVFwSDlMNWpGTUZtN1FsYkR2MTBGVjZCTTB2cjlMLU9kMUlnN2s?oc=5",
      "source": "csoonline.com",
      "domain": "csoonline.com",
      "published": "2026-07-29T07:32:42.000Z",
      "category": "Ransomware"
    },
    {
      "title": "The Case for Human Authority in AI-Driven Cybersecurity",
      "link": "https://news.google.com/rss/articles/CBMingFBVV95cUxQRFFVOUc5UGdHNmhqZ1RoVEpaRWlPcUJURXEzdlhXT0s3Qy14UVJLRjhORDhKR3ltWGMtMWNoRG41RkFwSmx1amRBT21lVmRNUHM3dlVENW1LeVQ1Q0dSeFJzcEZ5T20yNlhObWpsZUNvVHlGY3UwMjdmUWFOcUpPb2hfc3Zaa1o5VFFwVHRheGJEMWtmaE9ndEN2YUV5dw?oc=5",
      "source": "BankInfoSecurity",
      "domain": "bankinfosecurity.com",
      "published": "2026-07-29T07:20:11.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "Atlas: Wiz's autonomous AI Agent for vulnerability research, ranked #1 on CyberGym",
      "link": "https://news.google.com/rss/articles/CBMiaEFVX3lxTE1HTFE4T3JCM2VNOEozSm0zQm1lZE9Wb3FpU1VCYzF0d1lEeWtUSk5fUW42TnYzb09DZHRVT0M1NlNOUzhZX043SHBKYlF1ZmZPX1F3Tzc4SjVkSVN6RWFSekxnX2hDeFla?oc=5",
      "source": "wiz.io",
      "domain": "wiz.io",
      "published": "2026-07-29T07:19:24.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "Marquis Who's Who Honors Magaly M. Perez for Leadership in Cybersecurity, Security Architecture, and Business Strategy",
      "link": "https://news.google.com/rss/articles/CBMi_AFBVV95cUxPU193YlV0NlRvMUc0LWpSRGlnOWxxMzBiX29mUWtGR05iQUtiMnRjZGxOd1RZSk93eGt6bGtGWDhhV2dwVXBtcVhuZEM0VG01UFNWc1doMTlrM1R6NDhUcGdFOVQ1Y2Jpb2g2VkFsWlBqcWRRdEZRSjlSampSTUtlQlZsZVZCSldhd2tiX2Q1aXFwLTAwYnRhakk2TUVLRVUwWmgwZ2QtYWtMSTZvWG41TGRFazNuQ29SYUFyTHNDbVEwRHRCdnVrVjV6TnpyWWZHUDZDVkMyWXBPdVRPRWNhZ2o5ZHkxTWdyMlg5WVk3N0MwNmUxbHZkb3FwbnA?oc=5",
      "source": "24-7 Press Release Newswire",
      "domain": "24-7pressrelease.com",
      "published": "2026-07-29T07:01:25.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "OpenAI Agent Used Exposed Credentials Across Four Services During Hugging Face Breach",
      "link": "https://news.google.com/rss/articles/CBMiggFBVV95cUxPWEwzdWhXVjUxNHZtMkszdkxRamZPOGYzY1EyMHZoU1ZlZlBMOVFZVjBLRE81QVJzZnFpZUJsSDI0RVNzb2x4OU9ZWTNvLXltQWNRNVQ1bURRSDRDMm0zQVdMNWdMWTc5dEtYNGt4WUZQU1VJSVNSdkFkcHUxM1JkRXZB?oc=5",
      "source": "The Hacker News",
      "domain": "thehackernews.com",
      "published": "2026-07-29T06:45:00.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "ShinyHunters Claims Ernst & Young Hack",
      "link": "https://news.google.com/rss/articles/CBMiekFVX3lxTFAwSGxZM0NVX2pzNlFnQTNHUjQ3SWp1QnlueGoxT1BWOGhibHp3aU94VWNmTWd4bFZRWG5QdlM3dVc0eFJrSTJuUUpVRDZ3UkxfdjlLWmM5cllaZHR3Mm1QUjF6RFpCbkJfOTN3MGpyN3hwVWM2S2VYZW1n0gF6QVVfeXFMUDBIbFkzQ1VfanM2UWdBM0dSNDdJanVCeW54ajFPUFY4aGJsendpT3hVY2ZNZ3hsVlFYblB2Uzd1VzR4UmtJMm5RSlVENndSTF92OUtaYzlyWVpkdHcybVBSMXpEWkJuQl85M3cwanI3eHBVYzZLZVhlbWc?oc=5",
      "source": "SecurityWeek",
      "domain": "securityweek.com",
      "published": "2026-07-29T06:30:15.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "The energy sector’s OT cybersecurity talent is retiring faster than it can be replaced",
      "link": "https://news.google.com/rss/articles/CBMiekFVX3lxTE11NE5mcmd5Q1N6M0V0QVJzMmlBZ2VsQU5uNFlRaUNUT0xSOUhncDl3VjAxZnVqRWMzRUJsSzUxeU1Wd0xfYlp0cmp3RjhOZ0FXX3VuclZpVF9LbmkyMEFfYTFVZUNvWnpPcFlSdHdqMjFqbHYzam9KUlJR?oc=5",
      "source": "Help Net Security",
      "domain": "helpnetsecurity.com",
      "published": "2026-07-29T05:30:25.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "Sopra Steria raises growth target on strong European AI, cybersecurity demand",
      "link": "https://news.google.com/rss/articles/CBMipgFBVV95cUxNV051b1ZEMmFqZnJVUEsxMk9vUko3X2h6TkNVZnNGclZiS3lzdGJTYndMVDBrdmpFdWdDTGFPaHFqZ0VuSjFkZVhkdjB6cFlkOW5sMG1NLXZISmJtTU13YV9kUHNfMS14cTJUYWhFQmVDYkpMMURXZ001dVVqTlBWR21XdDc0d2s1ZldSY3I3eUtod01na2JpLTYwb1VZQ0l1QzZ3NjlR?oc=5",
      "source": "Reuters",
      "domain": "reuters.com",
      "published": "2026-07-29T05:26:00.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "BBIX and Getworks to add OCX connectivity site at Kagoshima data centre",
      "link": "https://news.google.com/rss/articles/CBMitAFBVV95cUxPdFdyTjBxZnZ6UXZrdnN0WFB1Tk5Kb2h4Vm1LeHBaeEt6SElaUDFEaGpGVVVvTnBWekNEb3IwUFVZWlNodUsxTjI2TEU3M1hncWVJQUt6YXBxY1otRUp3ZWg0WC1DN3l4eTNFa3dEeFdWSWdjdXllYlJ1QzVMNUNhaUxzdlMzS24xbzRoYkhtRm1CMzd4UGFvY2ZLd05ONndDQjY3Z0t5Nm0xNlZfUW5ZbmI3MDI?oc=5",
      "source": "Telecompaper",
      "domain": "telecompaper.com",
      "published": "2026-07-29T05:09:35.000Z",
      "category": "Cloud & Infrastructure"
    },
    {
      "title": "Coca-Cola-owned Fairlife resumes production after ransomware attack",
      "link": "https://news.google.com/rss/articles/CBMiowFBVV95cUxPXzZVVjFLMUxTVFRyOERGMm1hMWMzc0c1SmR4OUZ2Z2NTWWNCZ2lOYzF3MGhMaTFHaXZBVFFFbldWa1pPaklaaVJWZUZsYnpTWVJtaWdDNGU5RFBmVnliTzM1ME12UVRteVo3RGJfelc0UXAtMkVNblVoTHc0LW1vV0p2MF9zX19xNlhYWXdWQTJUVHNSYmRPZkFaSWxsQ1RxVC04?oc=5",
      "source": "connectedtoindia.com",
      "domain": "connectedtoindia.com",
      "published": "2026-07-29T04:15:23.000Z",
      "category": "Ransomware"
    },
    {
      "title": "Suno Slapped with Class Action Litigation Following Massive, Unreported Data Breach",
      "link": "https://news.google.com/rss/articles/CBMixgFBVV95cUxOMnlpdEhzSTJnYXU1bTJwMHR6ZnFoYXBRVmpjUXZBa3Q3SF8wenZNSGZYMkFxZDVmN1R5U281aGhLeVhQd0R4TVV5MDZod3l2c25CX3prckJRX3NFRnNtT2dXLVMxeUN0WTJXWHFDeUhnMEsySlZRWTJOdTVxaDZfcjhSenpvQksxUHZjclVRUGhxUnBXQ21WaXdUZ0FCZnlnSkl3dFVpQ2l4azlZRlc4czZ2N1djY3pqMVZTSGt0TUlDVGQtVUE?oc=5",
      "source": "Digital Music News",
      "domain": "digitalmusicnews.com",
      "published": "2026-07-29T03:45:16.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "Snowflake launches AI Gateway and security capabilities for enterprise AI agents",
      "link": "https://news.google.com/rss/articles/CBMi4wFBVV95cUxQbG9sZUNfRVpIRk90Z2ZPMUFMWk9Pam9pSTN0MDlWNTVnWVNRVWdVY1BXaG4tdHV0dEtrTHNJOVU0a2UyWlNnUVZibExRejRqenljWVRsN1Z4b09iMFpvclNHMGF5UFEzVmh6emxoNTVVODRXMW0wb0lqX0pqRTUzbHc2eG1yYTlBRTVxMEYzeXhHalEwdGJEYWtOTFJ2SjlmU0ZRQVNEdVRNc0tmWVFxNFBfejFSaTcya3F5OGI1UVVwMHVTREViR1JlcmVlNklMdmYwdzdtYUFCR3g3Q3JmdHlOb9IB6AFBVV95cUxQQUdOTVo5cHVSRVNkV24wRzEybld5NjI2Ukd1bXRKdkwwVHpRZEdnU1czUFlOekxJMEpob09rWFhhOFNXY085ZWVMSUY3bWg5M2VOX29IbkNIZVVDd0Zka2U4QlV6RWk3d3pnTGJRVlgxelFIRVRtMTg3Mk1BSWxBTnM4N1V0cVJOdmQ4XzAzQ2Q2MTRPMUNJdXlhMG51S1B6YWgwLWJaZ1l1QVZOeUFzX3VtNldaRzdOa3puLWd1cjhiQ2hZYkRNM2VJcW5YZTBYSF9yT3FOT3hpQ3Bwc1JnQXdsRDMzYThh?oc=5",
      "source": "ETCISO.in",
      "domain": "ciso.economictimes.indiatimes.com",
      "published": "2026-07-29T03:37:26.000Z",
      "category": "AI & Enterprise Tech"
    },
    {
      "title": "Does CrowdStrike (CRWD) Joining AI Security Alliances Redefine Its European Regulatory Moat?",
      "link": "https://news.google.com/rss/articles/CBMi1gFBVV95cUxPZWhsSGRKeTZvdFNYVGJLODRYVHN1ZGFvOFlkbDVOQlVfcW9ObHBweVZlWDBkU2VDX3F1ZTlkMUtMQzNZQVdDU04xT2x4Z0s5WHJRVWtQQTRhVmVPempoTjdtaktBRlh5eVJ3Uy1IQXM3NnZBem9iZFp3cXBmOUpqanBxQUg1MXN6eTdwMzJhLUhacVpHeTRJdWN5VEFCSjFlZVJCdDNNcGJjMHhlQkdXWC01blNDZE9nRnRJUWgwV19XRnNDN3JZT3U4VFJuekFDcnhkY0VB0gHbAUFVX3lxTE1wOWRoXzN0VXdSSnpYVWxXMTZLZ2VNa3dna2VuRFd1VmZmSDh4ZkxDcXlrYVlyRkU3UXJ4eUxCTnhsLUR0OVJub01WYmN1MW54ZHR1UVVMVV9fMkVneGZ0ZjN2UnJZcVA2Nzc1MmE5SnhLX1lsXzdQajlZdk5qa19PVjZXR3RWZm94SzJmUThfWVVqTU01Nk5Rb0pIR2hRSnNZb2puX1RpeXM2MUlVTkdWbUw1c2lGM096eTdKYlN0ZGY3YlA5OW1OdWFjRnJQbndjS3ZGNG5pZTFyQQ?oc=5",
      "source": "simplywall.st",
      "domain": "simplywall.st",
      "published": "2026-07-29T03:33:31.000Z",
      "category": "AI & Enterprise Tech"
    },
    {
      "title": "Singapore ransomware attacks aided by AI, Proofpoint finds",
      "link": "https://news.google.com/rss/articles/CBMilAFBVV95cUxQeXJUcVRnT09BM0t2MW0yb3VWSjNZRUhSMzFtUk9BRE5lb1ZvYWc0aTFoeUZCX0hrZV9xNFJfUVpoQXdpSzdER3RMZVpMNWYyd2RIaVBEZ0pLTld4aVRLczF3UXFwWmxsbmE2bkNSMjVsUHhDTlFBQUpkV3o0N2k3bjhLSC1yVENaano1WG8zYWxHNUxF?oc=5",
      "source": "SecurityBrief Asia",
      "domain": "securitybrief.asia",
      "published": "2026-07-29T03:02:00.000Z",
      "category": "Ransomware"
    },
    {
      "title": "Healthcare Is Undergoing A Cybersecurity Crisis, And Its Not Slowing Down",
      "link": "https://news.google.com/rss/articles/CBMivgFBVV95cUxPYlRsekxBZ2VFMld6V2REVXBkbGlJbHpCel9VVHVTQXFLbUdxcHloVmN1OThsNVdTYlVNVjZ3Q0hmbjlzYi15WllZSmVBVk5uTHBxRE9yVkMyTWVVckV3dWN4Nk5zXzU2X19tWlQtU3FZR01lUXVSbHhib3ZWMmp0X3V5WDlobU9naDl5azcxS1AxTzR1VGV4SE9XSmtWQ1NoZmREYUcyNHdMbXNIOGdQd1NfanN6VUhCbmRLT2xR?oc=5",
      "source": "Forbes",
      "domain": "forbes.com",
      "published": "2026-07-29T03:00:47.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "Microsoft unveils MAI-Cyber-1-Flash, promising fast, low-cost vulnerability detection",
      "link": "https://news.google.com/rss/articles/CBMiwgFBVV95cUxPdjlmaWtFQzJlT1RjNlJkd19xWHFhNTJkNkxYNWV3Vk1lMUFGNjlNZWR0RFhvSDN2cEw3Zzd1Q3lTNHBKZG9YR0hKYWhDRmE1Y18zcGNVZDh5ZzAtU3U5cE5va3Z5NjFaQmNlNlpQRURBbW5uWXZwbnNqTEhlSmxwOVNVSllxZmVFbExVaVVlaEtoU1FnZU1PWGNXOVBtd3AwQVU4QnMxNkc1R0N3YktBZzA1X1FHWnMyVU9yVjNZeGxzQQ?oc=5",
      "source": "Cyber Daily",
      "domain": "cyberdaily.au",
      "published": "2026-07-29T02:16:20.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "Fortinet’s new FortiGate platform converges firewall, SASE technologies",
      "link": "https://news.google.com/rss/articles/CBMiugFBVV95cUxPcUV1TDdtVlBDcGpKSC1Dc1oyLXpZYmVUOExBR0NxbDhyTXdZOFZXZjhMN3BoQWtsZ1N4M1VfYTB6NTlETjFnU0ZncC11Q254SVBYaGpCZWQxLV83aURDSmpfcktxalY4UnhZZnN3VE1yaXdrVlc5WXVleTAzRm1XanExdjJUTG92MDZSZjB0S2NQM1N3bElQZlROcDc3dHA5Rk11X2YwT0VWNE9EeDY1c1FUaXdib1JIa3c?oc=5",
      "source": "csoonline.com",
      "domain": "csoonline.com",
      "published": "2026-07-29T01:36:40.000Z",
      "category": "Cloud & Infrastructure"
    },
    {
      "title": "What every CIO needs to know about platform engineering in the age of AI",
      "link": "https://news.google.com/rss/articles/CBMiswFBVV95cUxOVy1meGJ1V1hMNzhBeDYyUmh6VVY3MkUzSjAzVTZpMFF6dXJoSWRoQ095cW43dTBaOW5MY2VscjZ2VXFHb04ybG52TGI1dFdEc3ZxU1g2NHoxMVBkeDRKVDQzRmZUN0dlMVVFOE9vd2tIYzNSa2NabDgtX0VkSjBTanVtNHFzYXgydzdFbEMxVGRENlZaNDBfanJ0OW9vZTF2Slk3ZmZscWo1Zkh4LXB6NHdPcw?oc=5",
      "source": "cio.com",
      "domain": "cio.com",
      "published": "2026-07-29T01:24:43.000Z",
      "category": "AI & Enterprise Tech"
    },
    {
      "title": "Scoop: Second account accessed by OpenAI's agent tied to cyber safety testing",
      "link": "https://news.google.com/rss/articles/CBMif0FVX3lxTFBodGRmd2V3VXpxOTFaaEtqU0ZiR2xPQkM1a29DZlhDRHZTLWxQOHB4OVBOckVwZnBTai1aSmhiWTZYaGNtRkI4eVpsLUZQa1poTk5waW8tSjBwdFNESWkzelBYWjhET0VsQ3l0Q21vbWdnRm9RdGZYVm8ySnU3eDg?oc=5",
      "source": "Axios",
      "domain": "axios.com",
      "published": "2026-07-29T01:00:13.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "A Quarter of CISOs Considered Quitting as AI Governance Landed on Them",
      "link": "https://news.google.com/rss/articles/CBMifkFVX3lxTE90c3Bld25NX0FtX2ZkbXpJWS12bXo3MWU2cDlHVFhDTlU4YVlOdWRJM1dKUjJPOXVpM2JKTEZJZnVWbHZtS2lUVU0tcmtpN3VDOEpCWU9ndkdkQVZ1S1VjVlZjSDNaRFlKQ1c0VHRQZ3c2RGx3T0VERWJTY3ozUQ?oc=5",
      "source": "Cybersecurity Insiders",
      "domain": "cybersecurity-insiders.com",
      "published": "2026-07-29T00:54:53.000Z",
      "category": "AI & Enterprise Tech"
    },
    {
      "title": "FBI Names Mythos AI a Law Enforcement Challenge as Exploit Capability Reaches Open-Source Models",
      "link": "https://news.google.com/rss/articles/CBMi3wFBVV95cUxQMUpSUVpJQk1obGh2Q0FuMVZJVDJfNkxydldxZFltMHJNWFlGYmtvbEx6MGZnSkdNalFuOXAwRkNkdWczQVJJSURiQ3ZmLTFXbEJVYWJlOTdJZ1V4Q01wejhScjBKOHV6Tzk4Q2ZKYWkwQkFwQXpQY3RhdVdBbmlRcjdrYXVtNHZxby16bVdPX3BkSkJqbmZwSm9UZ051SDJ0RzRPZ1Q5TWRVdjR3bTVFalp2dExiWHZSUW5HNGEtcUdZVndMOEpJVlFPV3Z6T1g1YTFocWhkSWhSR2EzMlRN?oc=5",
      "source": "Tech Times",
      "domain": "techtimes.com",
      "published": "2026-07-29T00:02:24.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "Zenity Launches AI Security Platform for Autonomous Agents and Enterprise Protection",
      "link": "https://news.google.com/rss/articles/CBMi1gFBVV95cUxPVzlwQ2Y0N0FMS3RTTENOdlZOb3NVVndpOG9tMFI0SnAzNEp0UnNLSmxjQ0VlczZ5SGNsNlB0WmJHcHIyLWhJMTBDSTgtUUVpSDhOSi1LOEhLeUdNcmpPdGJiZkdkSXd6UmU3dnVodHpHWlI2UjBJZUI5SmtVaDFrRDZzWkxPeDN1Wi1xbzFEak1QLXB1YnFodnlNaC1mSXQxTm1BZWl4Vk9GVGNDaEFYMjhlMlhScS02RlZxcUZ6RVpBcS1IQUlDbHJ5azhUWktWV0ROLVl3?oc=5",
      "source": "The Fast Mode",
      "domain": "thefastmode.com",
      "published": "2026-07-28T23:38:32.000Z",
      "category": "AI & Enterprise Tech"
    },
    {
      "title": "Rise of the Robots: You Wouldn’t Let a Stranger Roam Your Building. Why Let a Robot?",
      "link": "https://news.google.com/rss/articles/CBMiXkFVX3lxTE4wSTV0NndNOHdoNmRHYUpIcU5ia0E1OGxUZnpaaHJrZ2VYbHN3X0k0WUFHc0R0MUxvaTJaVDZna2Nyc0RwTWlXcnNGSWVfMjM3TFVtcjY0SjRMc24xU2c?oc=5",
      "source": "Pipeline Magazine",
      "domain": "pipelinepub.com",
      "published": "2026-07-28T23:27:57.000Z",
      "category": "AI & Enterprise Tech"
    },
    {
      "title": "NSF Supports AI, Cybersecurity Training at 14 Universities",
      "link": "https://news.google.com/rss/articles/CBMiowFBVV95cUxNcl9xeXNUdnd3bS05blFyZjBuVWtUclhWMzZKX0V1R09YbEtLS0JBT3Y2MmhJYWdObEhQOGNaS1ROVVRLTEl3bnQzaGtfbGJtUnU4RW9iaHU2QS1KSlRIMHRXbjNoRGlmWHBTMDd1Vi1HS0QyYXg5dUlZallmZ0d2SkNzbk9DSFNfamJKbEtCZmFCTUFURU5CbzVfa29CRzdlekxZ?oc=5",
      "source": "GovTech",
      "domain": "govtech.com",
      "published": "2026-07-28T22:47:59.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "Ghost Credentials Expose Cloud Systems to Hidden Identity Risks",
      "link": "https://news.google.com/rss/articles/CBMiogFBVV95cUxPaU9sNFZSb2hBOEQzVk1iTlZXOU9BYVBBaVJSNFgxS1dETmJBci1QbnRRUGw5WllqSFVCc3lvWm9vQldLUk9YUTNER2paRm9aejFoZGdDNkJZdFV2RDlTTjR2ekhENWlUNi1LV2RhN2FvU012MEtFWm9PNVNJckFUeGFsY01IZVVYQWhsbTRfbzRqRXNXUnJ5RkFMMWo5X05RNEE?oc=5",
      "source": "Dark Reading",
      "domain": "darkreading.com",
      "published": "2026-07-28T22:04:37.000Z",
      "category": "Cloud & Infrastructure"
    },
    {
      "title": "Authorities investigating a coordinated cyberattack against Minnesota water systems",
      "link": "https://news.google.com/rss/articles/CBMivwFBVV95cUxNY1B2QlBGZUttekx3bWhkdUNKaWF1U2hYS2JlU05XVTB2TExhVjA1bnlhY25HdXQxTzA5NFV3S3hxdkhueXNoLW55RTBUZ0thMnFLQmcteEhUOTRWOVZzTlVvNjZWcmJZRzBERm9wbllrRFRFSzI3NEJ2M2phaWJQTmtCTTBmTjF1bXBxY195V1Z2RU9SMzVSZGZfX2F0N2d0YXpibVdXMGxEY1djZE5ucUd2RTVBWldZeURkeG5GZw?oc=5",
      "source": "Cybersecurity Dive",
      "domain": "cybersecuritydive.com",
      "published": "2026-07-28T22:04:26.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "What To Do After A Data Breach",
      "link": "https://news.google.com/rss/articles/CBMidEFVX3lxTE1hVmFYU0J3RDQ5N0p0Y3AxZ1VQOGs4NDVuMm5TVXE1S2o3V2thWFl0MlVzTXFHVzFGNF84WU4xMXdoN0NBMy1UalVjTTk1bWN5Nms1ZmZPMGJ3c2tZZjloRVVmM0xTVjlIbmhtZktGNlVfWlRz?oc=5",
      "source": "WTAJ",
      "domain": "wtaj.com",
      "published": "2026-07-28T21:48:11.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "‘Mega breaches’ and AI drive surge in data breach notifications",
      "link": "https://news.google.com/rss/articles/CBMiqwFBVV95cUxOdUYxOURGSVhBZDJrazh3VURwV2syZGprWjlBVTdJVGRMMU01NWhDbThZMl96ZWpNWThhMjVnMlY1SlBHX2ZKMG5xa0ZVMHBnRU82eVNuYVdZRGNGdFJvRFg4Vmo4ZFRySmZiU3hta3VKdDVwOFJtTjRTb3lnQmNNdnloMjY5dWxpRGh0ODVqb1BwV0RkYm1aZDdPNVFNWFVwcHdxSWFQdzBRZkk?oc=5",
      "source": "WISH-TV",
      "domain": "wishtv.com",
      "published": "2026-07-28T21:45:00.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "Federal oversight agency urges FEMA reform, cybersecurity enhancements at DHS",
      "link": "https://news.google.com/rss/articles/CBMiywFBVV95cUxQUGRUS043c2xndGRrb0twYVNwdVEtMl8zejNRc3Zyc3dsZl93OXlTR0lnRm4yNklfbVJuT0I0SEpGTUN6SHBzLTVzRmhuMGlxSVNPZ1IwdVJwWS00TjhaLU5vLXhCSi1hdGZiMGEyUkJhTFB3TE82SDBxVkdmZ2NiWXRwNHF5QXdnQ19DZE4wMnYwLU40S0ZsbFRtU3kyQ3J3bHJxeEVtR1JEOWZ3T2dSUTdjVjI0YkhZTjJrSF90WmdBUmRzQmZ5ekZRMA?oc=5",
      "source": "theinsurer.com",
      "domain": "theinsurer.com",
      "published": "2026-07-28T21:41:49.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "CarGurus Consumers Drop Lawsuit Over ShinyHunters Data Breach",
      "link": "https://news.google.com/rss/articles/CBMinwFBVV95cUxQVHIxMS1xZS1jZmdyeFBhd0MxRElhSHZLeExWeGtJNGk4akN4bGpjemNqSFNIWWZTQlFmZjBnYm10V1VqS21nX3IxdTBnRmNXbWJteUZQRnFhaUNuOUQtekhCX3dDQ0NndklCRUJXXzl3cDh6Yng5UGNSY2ZzWENXb29vQjRkc0I3RV9iaUIyc1hpc240aXg5cjJoelR3Rms?oc=5",
      "source": "Bloomberg Law News",
      "domain": "news.bloomberglaw.com",
      "published": "2026-07-28T21:22:00.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "Ransomware attacks up 20% year-over-year as The Gentlemen and Qilin battle for dominance",
      "link": "https://news.google.com/rss/articles/CBMi3gFBVV95cUxPUF9yUmd3OFllMHlqMk1pTTBkRWRXbDk0dVZuREQtMFo1eUlKTWVrTGtSbko4SHg1enBELVhJNG9vRkc1UWtWbEtNQzFmNEF6ZkNXQzFUYlN2NVBNckN2V1ROYzJyQ3RYc3NHV0FPUHAzUFZQdk9MVWFuX3ViNDhuQWd1dTJGSzZqNG15ak45RzZXQncwNXZ4MUtSSTdhUDJnMVZMYV92eVVZV09WMnFfdjhwbmJRUVU3UTR3aUsya2N6WjluR1RYblhEZXBxeDZWZUVBQnhBZURCUFVxYUE?oc=5",
      "source": "DevPro Journal",
      "domain": "devprojournal.com",
      "published": "2026-07-28T21:20:58.000Z",
      "category": "Ransomware"
    },
    {
      "title": "4 people sue Maine hospital after data breach",
      "link": "https://news.google.com/rss/articles/CBMioAFBVV95cUxOTGV5VjJTbkVoOHp4U0tVdzdFTXA0LW1JZGIySkpJVlNueFNtbTdPZXk3a1Q0dm5jbkRLbzZ1MUVlekVQMFU0QlRfNWhzdm56cGxETDRhLVFyUXVyVHByclk1MXJRcWtNeWY5VWhVUTJMSW81RUhsb2otMXdnaWk1QzQxUkxaUFA0RGVjenhJenBjTFFlalFSOUJ6YkJMNFFk?oc=5",
      "source": "Bangor Daily News",
      "domain": "bangordailynews.com",
      "published": "2026-07-28T21:11:38.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "GAO Urges DHS to Address Cybersecurity, Disaster Response Recommendations",
      "link": "https://news.google.com/rss/articles/CBMimAFBVV95cUxOalZpUHlfTUI5a2xBVzlkMzZ3N0w5eWMwcWphZnZFbE9TZUZxZXRMTDhQQWZuOU85a2dDWUJPVnRpN1FST3hkZjhVd1pEdEZaWmZKUEM5S0NfNWFldmR3cmRDd25GT0lqZmZoSHJIempWdTloanZTMFJ6NmxHbFlYcEo1VXRkcTlmVVJQMmhMWDJPeTMxaUFOag?oc=5",
      "source": "ExecutiveGov",
      "domain": "executivegov.com",
      "published": "2026-07-28T20:59:11.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "Coca-Cola's fairlife production resumes, cyber hackers claim responsibility",
      "link": "https://news.google.com/rss/articles/CBMiwAFBVV95cUxPU0s3dVFRa3FhMVAtZTlkT2pOaDdfRm9NNUZyYmR4cVUxYVlUV0NjQmVsRjlPYngxVUdvYThZMGxsUFczMHo2TmpyMk5NRXNqVFFHai1wLVlWZk42dFg4ZnV4TVZVYjRqZFU4TkZDbXpBLXZOa1QtQmdUZndnaW1GYnBldzFQQkl1WWZ0YlRqUXF2Yzlfak80VjkxcnN1ZVdQYUhvd0RiSGNrMTQ5c3ZqbUJ1NklaaVdZNUZrUUd1TXk?oc=5",
      "source": "Michigan Farm News",
      "domain": "michiganfarmnews.com",
      "published": "2026-07-28T20:34:00.000Z",
      "category": "Ransomware"
    },
    {
      "title": "AI Agent Security Just Had Its Catalyst Moment",
      "link": "https://news.google.com/rss/articles/CBMilgFBVV95cUxNS2wxenYxQjJLdDFJMTcxMi0xQjBOWWtIRHR2SHNmRWtENHBxWndyX3VjVlpmRFVWbnF6UDd5MWtEaFc5NzVRZkVfY1B4TUhGVFlRSFB5NmhITFRQeF81cmhoc3ZPR0ptcS1Na2h0Y0tMd1dGVGdudk1BaWZjN2l3bGczcmxIQzBQa3U4UjhkWVMwRV9hUEE?oc=5",
      "source": "Check Point Blog",
      "domain": "blog.checkpoint.com",
      "published": "2026-07-28T20:09:00.000Z",
      "category": "AI & Enterprise Tech"
    },
    {
      "title": "Data Breaches Are Getting Bigger and Companies Are Telling Us Less",
      "link": "https://news.google.com/rss/articles/CBMisgFBVV95cUxQbUMtQTJJVDYzU0RCVE02N3VtNGlzb0x3LWtlcW1fb3RueVpMMUVwS3dJbU0tN3RqZm8xQ0ZsdVdMTnFXaFlySjdfdUgtbTBtZ25vYUhWcUN2aFNsSlk2MEYwZmNORUQ4czBpaHZ0VDVab1pSUlpRb0o4VDFRMGtKbFlqNDNjdlZSM25iSmw4QzM1d1JOdXZoQThpTXNTTnRBQUp6U2hoYUppd3lKcWRUb1Bn?oc=5",
      "source": "CNET",
      "domain": "cnet.com",
      "published": "2026-07-28T19:41:04.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "Azle Smiles Data Breach Exposes Health Info, More; Lawsuit Possible",
      "link": "https://news.google.com/rss/articles/CBMiekFVX3lxTE5rYXR6b3dzbzZ6c0d3bXc1RFJwcm9tUHhObjdBRXZJb0RjQy1jekZMNWE3THM1Z3gxZzQzajhBREZocG0wVXh5aFhYVERiR09pOXdVRFY5LWQ4ZVBaOEMxa2F1OXN3ZS04ZWdWd3QxcmpqeWtjVW5Nd3JB?oc=5",
      "source": "ClassAction.org",
      "domain": "classaction.org",
      "published": "2026-07-28T19:26:48.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "Microsoft Launches AI Security Platform Promising Faster Vulnerability Discovery At Lower Cost",
      "link": "https://news.google.com/rss/articles/CBMijwFBVV95cUxOSi1uZ2JvcE5iSlFIeGxNWGg4akxYUF9XeWR5YlNVMFhiVHJGNFJOZUtOdGs5U1U2S2ptakxrMnExNHF1bUt2Vk4xYmV3SlNXczUwQnN0emh2Y3RTenZoamRLeG5SS1cyQ3VkSktDNXNRSkY2aFpFc1ZUTEJnbFVDSV9OMUhwcHdoSURiUTE3OA?oc=5",
      "source": "LinkedIn",
      "domain": "linkedin.com",
      "published": "2026-07-28T19:06:39.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "Introducing Cortex Cloud 2.2: Accelerating Critical Response Across Posture, Runtime, and AppSec",
      "link": "https://news.google.com/rss/articles/CBMiekFVX3lxTE1MUHJnMVl1Q3Q0M2pKNURNWmU2RU5Vb1FUOXJfS3FiNm5qVHJERW5RNHNXcTU1VXN2ZHgyUnNtQXhibjlaMkxJOGZsZkduSnh5QjlrSWhBRkVmYlFTdU0zQTBBT1NHTk8xRFc3TldPQmtwT2RQZU9neGNn?oc=5",
      "source": "Palo Alto Networks",
      "domain": "paloaltonetworks.com",
      "published": "2026-07-28T18:29:38.000Z",
      "category": "Cloud & Infrastructure"
    },
    {
      "title": "Check Point SmartConsole Authentication Bypass Technical Analysis (CVE-2026-16232)",
      "link": "https://news.google.com/rss/articles/CBMiuAFBVV95cUxQREpNLWVoQkE3ZGxwOHJPNWd5OTM5R3ZSaDBXT0VCMVhkNFNqa2p6dTltdXI2T1hiNUlVOTBMZ2dSLW50VFpEaTFCUFF6aktxbTYyeDR5OWxXdU04TW1kYTlGQWlCdHFwN0NLMDVrQm8xRnB6SnVlWWt1WXgtbGJJVTUxSVVoTTh3cTB1dWdENm9NLTFkMVgyTGgzVmlkeEtvZWRyWllXR3pvNjNKLTVHVGc4U2NoQ0Yy?oc=5",
      "source": "Rapid7",
      "domain": "rapid7.com",
      "published": "2026-07-28T18:26:31.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "What to Expect at Solutions Review’s Spotlight with HPE on August 20",
      "link": "https://news.google.com/rss/articles/CBMisgFBVV95cUxObVBnYmE2SVY5UE9mR2lnMV9taG1MalVDVW9LRmVoYjVxU0UzX0otYjF4ek5ZaVF0bld3WGlLaktWR2t2M05PMEluVjdLNV8zSGRDcXhxTVdIVTVjWV9Rc1FfQS1OTnR5c2Vob0hJRWpvdlBLYlE5NWhObkp1SWZZdEl3NVV4THk5aXpxUkoteDZjSW5WSmhYcUtOdEYzdV9XZjhOY25JNkFweGdSY3hNVmtn?oc=5",
      "source": "Solutions Review",
      "domain": "solutionsreview.com",
      "published": "2026-07-28T18:12:18.000Z",
      "category": "Cloud & Infrastructure"
    },
    {
      "title": "vBulletin fixes critical pre-auth RCE flaw with public exploit",
      "link": "https://news.google.com/rss/articles/CBMirwFBVV95cUxOSzRTYVZTQ19vOUluREtId1hRdnlRVVl6Xzd2VXRwSXhiYTFpMDRoR2V6aTFaOE5RbHMzOHg4aFk0X1lkd3lqZGlLbXhhRkhwS19TSFdHQWk2dEpZTDd0czJkbTdLMGNiRUJBYWcxNGZpRVJuSXJlMFZVWGg1N0psTVhoX002eEVRYjNOdjRKeTdXS0lxY1hqd3hCbG9adW5GcnJrdzBHRW5jamhBUzdB0gG0AUFVX3lxTE9DcTZyc29sY0hwMXZYMjNUblQ4MVFTOUtrSkRnZjJBSkk4dmJsNFNOdGdrb2gyVXFkTGREbzJpTndyMF9IQVdyZy13OFJkc1JFN3gzazVpTGxOWTZyc051NXQ5SGdQNkhWSlhhZzNkSngzZUNDTTNMWFlkVmlSQUI0X0Y4ZnJqeWY1Mm5tOTF2WExGalYxTXJkMUxwdFZMNlBmM0NVQklhLXNrbzlRcndQU0FKcw?oc=5",
      "source": "BleepingComputer",
      "domain": "bleepingcomputer.com",
      "published": "2026-07-28T18:08:50.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "Saint Paul overcomes ransomware attack with help from Oracle Cloud",
      "link": "https://news.google.com/rss/articles/CBMiV0FVX3lxTE1VV0NPY0g3RkZGQm1Ccjk5Yy04bHhKMWNJcE9KVGhjUXZScWJtbmRDSjM4elp5OVVxaU51d3hDYjh2RDhQTHZJdEZZaTRlRDYwUWRkZVBuYw?oc=5",
      "source": "Oracle",
      "domain": "oracle.com",
      "published": "2026-07-28T17:43:03.000Z",
      "category": "Ransomware"
    },
    {
      "title": "Suno faces proposed class action lawsuit over data breach",
      "link": "https://news.google.com/rss/articles/CBMivwFBVV95cUxPVHZwbkRFeG9yS2NRMjJrT3R2bDNMOVppcVJpa2hTQlBrZ0pMajRfazNPb3dScEFqa2RvNlRSeEtTalY0bndtallVQUtDMElaQmRTUUozM3JjU0FGaHdvdkFmajUydVM4eDN6c3R2WXVya215ZmhUZ0c4ODNPRkNjZFhTT1BoZzllRV9ac2VNazZ1NTN5ZXRSXzdlSWc2RjNaS1kxVzZXdFZPNzM0VEtVSkVmemFJTVA5SGg4czRIbw?oc=5",
      "source": "Music Business Worldwide",
      "domain": "musicbusinessworldwide.com",
      "published": "2026-07-28T17:19:22.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "Illinois cardiology practice sued over data breach",
      "link": "https://news.google.com/rss/articles/CBMitwFBVV95cUxQMTE2eE5nb1hSbk9XSDlIbEVoc0NHSlQxa3BtMjJ3eDFzS2V4bDF4dEl1TzNrMTlJbmFjSmQyWDlwdjJvbUNaRjM3UUhWVWNzYUR4VnVQX2I1b2dDQXUybVVUWGFXcVVIZG1GSXVFNzVvNXhGZjMzRl9FUWFkV2RCNnJrdTdJN3o3akVScW9ybXpuWTBPZ2VyMzZ1YjZNdW5HYTlwWjlzbmtSUjFiYnRlanh2N056azQ?oc=5",
      "source": "Cardiovascular Business",
      "domain": "cardiovascularbusiness.com",
      "published": "2026-07-28T16:19:55.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "ShinyHunters claims EY breach, warns all stolen data will be released",
      "link": "https://news.google.com/rss/articles/CBMiekFVX3lxTE1US0JjVEcxb0ppaEw5TExhU3lvOEtQQ1ktampqVkpJcE5JQnJSbkJZeEdQZEpxeFptZDZpSVBtZ291V2NGRm1LbjBHUE1mY0lYSmhXQWg2U0dTVlNHUnhNcTV3X2dJalE1ckV6cTdsRXB6OHBsN29ORTZ3?oc=5",
      "source": "Cybernews",
      "domain": "cybernews.com",
      "published": "2026-07-28T16:14:15.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "All about Oklahoma’s Security Breach Notification Act’s newest reform: SB 626",
      "link": "https://news.google.com/rss/articles/CBMihgFBVV95cUxQYzQ0b0NsYVVXOXpraV9UM0dnamM5V2lGOWRfbzl0ZVYwdEhuNDk1Vk5XMzlXbVFXOEtKSHV6Wms3QkNYU3A1eUVnNTN6V1JKRHpBbVdzNG80a0tHNzF4dTRWSC1zLW1MTmtYLWhVLTVRNkZOMEFNMHJ5ODFsa1RLMHRzRmw0UQ?oc=5",
      "source": "JD Supra",
      "domain": "jdsupra.com",
      "published": "2026-07-28T15:49:39.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "Cloud Computing Stocks: Find Top Cloud Stocks And Track Industry Trends",
      "link": "https://news.google.com/rss/articles/CBMie0FVX3lxTE12Yjh0N3dEWUZIMmV3X3I0Wm4tb3hUVk4wQ1RFQi0ySm9HbXJBQjRaNDdPN2hqNEFXZzNRWkplUFNOQWh6WmVfLUVzS2FFWVh0eXJ6dXRkVzFtUWcxMFBkSHhWb1VaUGkwcjBTclJaU1JDcHB1eUJrLTFJMA?oc=5",
      "source": "Investor's Business Daily",
      "domain": "investors.com",
      "published": "2026-07-28T15:42:00.000Z",
      "category": "Cloud & Infrastructure"
    },
    {
      "title": "Nvidia backs open AI security alliance with tech giants",
      "link": "https://news.google.com/rss/articles/CBMijgFBVV95cUxNaUJ1RGxxTFUyMzZFdDZ4RnZTRUlJU3A5U2RRSTV2TXlXczhySFJGZThvZlRJMlJjWUhzV0ZsNG9fVnBtX1pvU0xCWVpPNkoxMHBzZE45NDFYTWlvTVRfNG82VjVUd1NwUEJwelBpNl9oV0ZHSDFUNktQR1JHY2F5VlAyNmRrRE1pUzQ4WTRR?oc=5",
      "source": "datacenter.news",
      "domain": "datacenter.news",
      "published": "2026-07-28T15:39:00.000Z",
      "category": "Cloud & Infrastructure"
    },
    {
      "title": "AI-found bugs aren't proving any easier to exploit despite the hype",
      "link": "https://news.google.com/rss/articles/CBMivwFBVV95cUxPQ2RWU1l4QmUtNUJ5YldvYkZTWXJhalhxVkhiQjFUaFktUzlBWFV3MFB1YWNMaGdKMmpzYThOc1VZaEFIRlE2aHcwYzBQVTNxOXBXcHlJM3BOLVlCUzFVdzlKcXRSVEpuNFlnaHVkSnQ5QVR1bHU4eDBtWEhDcGQ0TWhmTWI4NUFYdWY2WkhKSWNUY2JlNGZPSVl1X2ljVGdfSzJ3MW1wMHNHc08tdnZwb2hjREowazdDLUwzMHZMYw?oc=5",
      "source": "The Register",
      "domain": "theregister.com",
      "published": "2026-07-28T15:26:41.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "Snowflake Launches Cortex AI Gateway and Advanced AI Security at Black Hat 2026",
      "link": "https://news.google.com/rss/articles/CBMihwFBVV95cUxQUzlBTHBTNFNIdG9JSGdJMUN4V2ZZV1BtNEotaS1qRVB6X3d0M1NNWTFIQW9NVm5vQXhuUnA0QXpMVFd4dzNFYWhzNnoyZFcxbGtrWUJ5MmItVkJqeHJ0Vjdjcm1hbUtJanJvUXBCZjhwNFFscTZhdzk1SGNtZjhXZE5sU1VMYnc?oc=5",
      "source": "Snowflake",
      "domain": "snowflake.com",
      "published": "2026-07-28T15:04:27.000Z",
      "category": "AI & Enterprise Tech"
    },
    {
      "title": "America’s Data Center Boom Is Commercial Expansion Disguised as National Security",
      "link": "https://news.google.com/rss/articles/CBMiiAFBVV95cUxPODZZbzNVeXY4bkxuQnFkOW5iSm5NZWRubjRkS0pyYXE1UndVcFBnYlVpREV4dV9URV9WU1g2WFlfNnZvV0NaOXBMR3Nva0RwdzlabEdzVUVZMno1Rmp2VUJaSFl1eFRtcmxFY2tMZ0xVT1NWeUVkeWxfUk1hdWRHWUJJdFFUc19t?oc=5",
      "source": "Dr. Robert Castellano's Semiconductor Deep Dive Newsletter",
      "domain": "drrobertcastellano.substack.com",
      "published": "2026-07-28T14:57:53.000Z",
      "category": "Cloud & Infrastructure"
    },
    {
      "title": "Data‑First Security Strategies for Enterprise AI",
      "link": "https://news.google.com/rss/articles/CBMidkFVX3lxTE9Qb2NHaGFVZHFpMTZjS1lBc0tyOGF2NUo0M0JmdzBmajZvVHNmeXUxVFF2aGZhdFJiZVBvazhJMGY0VzVJTTF6d1ZlTjVSbFk0cEZyZFAtVHJZc2xvckdhSVFtd1g2V3A3UW1VY3A1QVJrMmtmMUE?oc=5",
      "source": "Emerj Artificial Intelligence Research",
      "domain": "emerj.com",
      "published": "2026-07-28T14:56:12.000Z",
      "category": "AI & Enterprise Tech"
    },
    {
      "title": "Origin Energy Data Breach 2026: Analysis of Cybersecurity Incident Affecting 900,000 Customer Accounts",
      "link": "https://news.google.com/rss/articles/CBMiygFBVV95cUxPMks0aWlINng1V05scGMxVkIwS21wdXBMTTJhc3I0QU9PTFNndzd4X0lqREdyQ2ZMcFBFTjVOZlBQWkRhMmRHRFNzY29udi1fMDFYUHEwS1B1SzdDNEN6Umo3c1ZYV2laai1RUWR1SXdNQUgzLUxaRmZRVTl2aHozdjRoUUs1N3FIQ0ZJeVRielYya3hOMXJqU2V2WmZPYl9qNUV4VE9hc2JhQ2lBd2lMSzduQkY1M29rWk4wclBBMk1XRFZIYVQyb2FB?oc=5",
      "source": "Rescana",
      "domain": "rescana.com",
      "published": "2026-07-28T14:54:25.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "Did ransomware attacks really decline? Here are your business' 4 best defenses",
      "link": "https://news.google.com/rss/articles/CBMiigFBVV95cUxOTmpKd1d0eUpXVmdVUDF4akRpbVliZS14OWR3Z3N4SEM2OVdaQU9WSWRGQTROU1dhSzVhOVNLRUQ2akJ3ZWZnbElsYU9oN05wMG51VFhoMU1Oc2VadFc0V2Q2RWdSNHRCVVA1Y1JpUEZsaVk2b3lzRm1TWVpUaHJWUFAtMDFzLVI4TlE?oc=5",
      "source": "ZDNET",
      "domain": "zdnet.com",
      "published": "2026-07-28T14:21:00.000Z",
      "category": "Ransomware"
    },
    {
      "title": "Coca-Cola restores most production capacity at dairy unit after ransomware attack",
      "link": "https://news.google.com/rss/articles/CBMiuwFBVV95cUxQVzJZalVsdF9sOVZmaVdQXzJoTDk1aFpQQUJ0VmRVUXpjSmhxdkRXTkg5OVdrRVlqOGJtV2VsaEF2ZmRfdklUcW9iNlp2ZEdUTkZVS1pHRkdTTndpbkM1R0pnWnJnbXdCdXZPenhKVVdZTnVIWFNhV1RmRGNSSkc2dUYtbmNrZnRzUHYtVUxLdmEzakpQNXFONFhOb3Q3ZkxXQ2gtUDFUc05XTGg1a3hvSjkwVW5fazBzUTQ0?oc=5",
      "source": "Supply Chain Dive",
      "domain": "supplychaindive.com",
      "published": "2026-07-28T14:09:33.000Z",
      "category": "Ransomware"
    },
    {
      "title": "NSF announces first awards to advance AI and cybersecurity education and workforce development through CyberAICorps Scholarship for Service Program",
      "link": "https://news.google.com/rss/articles/CBMiggFBVV95cUxNT0ZTMkV4U3V5R1BOUFJybmdKaTlnZWVRTlBoRW1mUHZGcnpRNW5MUmlBeHk5WkdrTUFkdWd4T0dERFduSWU2OW0tcFowY2ZIRlctQy1qRWtLUWNfUk1Wb3VJT1V5LXBwTGR1eTZEZGs5ZjVILXRGeVJ1VV9RY1IxOEp3?oc=5",
      "source": "U.S. National Science Foundation (.gov)",
      "domain": "nsf.gov",
      "published": "2026-07-28T14:00:07.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "Fortinet Expands FortiGate G Series With New Firewall and SASE Capabilities",
      "link": "https://news.google.com/rss/articles/CBMitAFBVV95cUxOVEt4dUs0MUc3ZW9fMFBBQmZMcTBPV3FVc3Q3YnQ3eFZ5MmRIRHJ5NVI1VklhV0EwNkpyNmNCaHE3ZktBQ1ZkekROLWlsTTUwT3JRTXhGSVJ4YzZKdU81bDRicXFzVUZTTnFqSHdQWDJLT05ZS0NZOVFjY0RQQkY5NV9pUzdEci1EZ1Q2X0xROVhHbWhGNlA5S3R3ZFFjYmFwOUlSSmtmcF9xV2VLTlNOTlUxSFU?oc=5",
      "source": "citybiz",
      "domain": "citybiz.co",
      "published": "2026-07-28T13:52:52.000Z",
      "category": "Cloud & Infrastructure"
    },
    {
      "title": "Exclusive: Dymium introduces single gateway to govern enterprise AI use",
      "link": "https://news.google.com/rss/articles/CBMilwFBVV95cUxOTmNyQ2w2c01UYm5ESDdodC1Bb2hWeU8zZ0U3UXZRZHYwRjFlTEFWcS1kRDktMXhqejJEZzZfVmlLdkZTbmkwYUNWLXltVXctN0twZmI3UzZvdmhFYlkzQ0tqSzVMdnF3XzlFWGN1eE9Wc2p3QmlsMGtpVW9URThMNDlRcF9vb1c4dTFjeE83WTJSZnByZGs0?oc=5",
      "source": "SiliconANGLE",
      "domain": "siliconangle.com",
      "published": "2026-07-28T13:00:39.000Z",
      "category": "AI & Enterprise Tech"
    },
    {
      "title": "Cyberhaven Introduces Flow, an AI-Native Data Security Platform for the Agentic Enterprise",
      "link": "https://news.google.com/rss/articles/CBMi3gFBVV95cUxQc0hlR2ZhNU9IM25Tc0JPSERoYlctYTBaR3pFbjg4T2dYTmN6b1QtYmY1c00zT0ZHVjZ3QTNfMktfQlZxUm83anc4VVV4VkUxemU5d2o1TEQ0Z3BvY3YtUlhsWHl0OUF1ZFBheUFVUnI0N3E2RDhKUm9kMEkzR09PN0VTZEROb3N3dWd6ZngzZnlqVWNRT1h2M2tCc1RwV0MwRFA0NEFzVDdnODNBOXR1M0pJTHBoQ1RUWG0wSF85LW9OaUpzNFVKQ0VDRU5qUHZOaVlLczZ5Z3VhUFZNWnc?oc=5",
      "source": "PR Newswire",
      "domain": "prnewswire.com",
      "published": "2026-07-28T12:35:00.000Z",
      "category": "AI & Enterprise Tech"
    },
    {
      "title": "Coca-Cola confirms hackers stole data in Fairlife ransomware attack",
      "link": "https://news.google.com/rss/articles/CBMingFBVV95cUxOR2ZRUjQ0NGJTUDgwSlVTamVJSnYzQW1lM0dqbFFKX0g2NWYwdWgzWk0xSTNKeTZKRHY1Y1RSNEptOFJlejQzZnJYemR5ZjJRRnVCRGhjN0U4WWJvanBkMXY0eXVoM1FJNFZfNnN4azkxdVZpTDFWWjBRdGFGUWdBRVBKejNUUExjaUxGX0dveldKajllMlJKcTVkQk5nZw?oc=5",
      "source": "Help Net Security",
      "domain": "helpnetsecurity.com",
      "published": "2026-07-28T09:01:05.000Z",
      "category": "Ransomware"
    },
    {
      "title": "Is Business Security in the Cloud Going Up?",
      "link": "https://news.google.com/rss/articles/CBMitAFBVV95cUxPUnFUa2s5QlJlcUhxRE5xSzJnNzJyaDdPdWNWZURRaUlid3prTkxlU1ctd0FxZ2hxMnF2NDZBNjJLX0ZieGs5bjF3Ync1SXZHVTlnSF9IVkw5akpFZ0s4UFhaV3BUU05faGZHeGozYnVkTlZJWldlSmhOMDZCa3VaVHNXN19VcnQ2QzAwMVdpVll3SFVETFlxQm9DdjVYNnBLa2NPYTFaRG9XdlFOWEJucDN0TmI?oc=5",
      "source": "CIOReview",
      "domain": "cioreview.com",
      "published": "2026-07-28T07:29:20.000Z",
      "category": "Cloud & Infrastructure"
    },
    {
      "title": "Unpatched Fastjson Vulnerability Exploited in Attacks",
      "link": "https://news.google.com/rss/articles/CBMiiwFBVV95cUxOWk41dExXOFlJV0RqZzVaNDRSNkpIamk2WnQwc0VXR3Z0RjVhck42LWpwRTB4RUR1TG1lZTNheDdPajREUXRNb09FcG1PZmdXWkRHeVFxbFNDVTBFMWFaYWpBVnd1eno1dzdZNGZ5aDhfZnNiWl8tZmRLc21GTDlla01TQmowd2RDcEUw0gGQAUFVX3lxTFBkS1hHd2pxeFA3bjdWSWotRFRnNzNQYTBXUjhITGRNREFLNmhoVWhpYWxvWGJraDBBTGdORjZuZlVJaldvM19NM1VKTVQ1bHRMVXlWbG15NDRsdmlmaFE2bExMbjBva2stNVZiQzJYX0VvUnhiZ2xYY25YemVveE1BOTBnV0djM3M2VFNKbnBlTA?oc=5",
      "source": "SecurityWeek",
      "domain": "securityweek.com",
      "published": "2026-07-28T07:27:55.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "Attackers Exploit Arista VeloCloud Orchestrator Command Injection Flaw",
      "link": "https://news.google.com/rss/articles/CBMifkFVX3lxTE5pb1hqTlE1N1BDYUJYT3BMaGotcThlRmlyZDNsVzYyREJFSmxxSGc5YmVLZW5XcWdXNV8ya3hiVkFMYmplWmdOYWdFcGNsNXI2SEZjLW5Dc1pqVzFyekxsZXJuajAyaHVBNjV6VmpLYXI3akxUN1JBdVA4ejQ2QQ?oc=5",
      "source": "The Hacker News",
      "domain": "thehackernews.com",
      "published": "2026-07-28T04:43:00.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "Verizon takes on $1B dark fiber data center deal with Google",
      "link": "https://news.google.com/rss/articles/CBMiswFBVV95cUxQbWlPa3NuZGxGUDNROVhSMkJ5bHd3ODZFM1RfYUtwNG5RaHhPNl96RGp2cWNXZ0R0Q3dNejNiQUJTRmpqTDhSNFhOeV9Yak1hREVIVFdNN0YzdkNVaVFuMkZHWVBMZEllQWdSUEpKQUtDcXhMNk9vUEpmdzNUdk1qeWl6U0J4Q0tlX2VvTm0yeWM2S0xoTVU5cjdmSEJNOUtzUFBZTjNWY0M1QktCMFk1U1gyUQ?oc=5",
      "source": "Lightwave Online",
      "domain": "lightwaveonline.com",
      "published": "2026-07-28T02:02:37.000Z",
      "category": "Cloud & Infrastructure"
    }
  ]
};
