/* Auto-generated by news-fetch.mjs — do not edit by hand. */
window.VT_NEWS = {
  "generatedAt": "2026-10-04T10:00:06.078Z",
  "window": "24–48h",
  "total": 72,
  "last24": 48,
  "sources": 61,
  "categories": [
    {
      "name": "Cybersecurity",
      "count": 14
    },
    {
      "name": "Data Breaches",
      "count": 14
    },
    {
      "name": "Vulnerabilities",
      "count": 10
    },
    {
      "name": "Ransomware",
      "count": 11
    },
    {
      "name": "Cloud & Infrastructure",
      "count": 9
    },
    {
      "name": "AI & Enterprise Tech",
      "count": 14
    }
  ],
  "items": [
    {
      "title": "From banks to lenders, suspected AI hacks expose cracks in Korea’s financial defenses",
      "link": "https://news.google.com/rss/articles/CBMi0gFBVV95cUxQUlN4N0kwQXl3eUozQ0JSUFJsb0xmTE1qa1Q0aFpELWF2cHVjR3haVmRiWVFiR1dMTENBLUlvRjBGTmZ5U2ZSaFRCeVVmVko1MjYzTTVlT2ZVNW5obm85WW5KekxRSlBHN0dQT0x0R1QzYnZDTWV0ZmFwQ0t3SDRLR1lrZHBYQ25YXzB6eHJ5UGJMdEMzSnhwbXNmQUl0NVJXQUFPUDdHakJaZ2tKNEktOGRUV1ItQ1VxbEwxeVNGQTdvZHRnY01qa1k1WUN3b2RpSmc?oc=5",
      "source": "Korea JoongAng Daily",
      "domain": "koreajoongangdaily.com",
      "published": "2026-10-04T09:49:58.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "South Korea investigates data leaks following cyberattacks on banks",
      "link": "https://news.google.com/rss/articles/CBMijwFBVV95cUxNMjczX2FtSnpLOURkN2pOZGliVkkzM19lZzN0Q1oycHpaMHBLQW5vSWRBQ3N2NFJuamc1ZE5aSDhBRG91NnJSZmZNQVBEZ2NQSVpJclVWbHpBNmZraTFlc21HVTZCMzRRS0NDTkR6T1BoTHBmNERfVTJfcUxrd1J3VFo1eEtMYnBsYmo0cGlqY9IBjgFBVV95cUxOWjRHTmVxMjhOaWFtSVUwbXVQdTgydU9GUTFsTjFaSk9rc3JZRHhqeDVzN2lTeFI4MzBLX1loRFNUZVZoamcwZnFiamQ1WUxsUnJmWWpoSDBrNFV5amY4bzJ3ZzZTTWlmS1NBT3NLS2psR2RyclhlekgtdWVyUGFoYXhDNGQwRlJmZUozd3V3?oc=5",
      "source": "Українські Національні Новини (УНН)",
      "domain": "unn.ua",
      "published": "2026-10-04T09:49:10.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "What the Recent Frontier AI Incidents Mean for Security Leaders",
      "link": "https://news.google.com/rss/articles/CBMiuwFBVV95cUxQamhoZFBUR2JiUE92LXVRUFFTXzJsZjZ1aXA5ZDRRTmxibjFVRlhKSWltdGpTdnA2YUlkOHdqWkhkU2dsWUk5UThyTGc1eFphR05acTB0UlROQzExWmcxMXNZV0pPdFZ3NFZHcGxRcXh4OTd5ektoSWNfZVdJd2EwSFd5VWRmSjNCaDR3dXN0R2pKU05yWlg4RFZhancxSF8wcXd4SmltbXJlVEE2bWVVaHFVd183eGpFbG5J?oc=5",
      "source": "GovTech",
      "domain": "govtech.com",
      "published": "2026-10-04T09:05:22.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "Seoul steps up cybersecurity response after bank data breaches",
      "link": "https://news.google.com/rss/articles/CBMiiwFBVV95cUxORnVlTXZfdWVXZW1UbjZYOXJlZkUxckZmdm41U2lJM3FackFvZWZ5eUw2ZEtMblV5ZG9xV05nOTJOaXVJaUFxSnBuR2czT1hXOFhPYUszMHJhVmVOcmNDdXpIM0VZUHJhWG5wNUpNT0dkVUg0ZFMySm1ScUwtSTJ5bWU2WFg2Z1BqYkVn?oc=5",
      "source": "Latest news from Azerbaijan",
      "domain": "news.az",
      "published": "2026-10-04T09:01:45.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "Need Training on Cybersecurity? The Hague Has it Covered -",
      "link": "https://news.google.com/rss/articles/CBMimgFBVV95cUxOWGN3QmRVeFZFYkhKdUtlTGRlOGk0UTVhUXktY3NPbDEwYjBmOHhGd21YbHpwM3dBakRRWHl6U0tGQmhJMU40eU9USkVMWDA5QlA0S00wSDNqYzZCS05UNEluWXZnUWV5c0JFTEhVZGxYZU01aHdaUkwxaUxSUktlZTZqZXhYdFFJMmg2MXI0c1J3T2dLdHJIcVF3?oc=5",
      "source": "insurance-edge.net",
      "domain": "insurance-edge.net",
      "published": "2026-10-04T08:52:58.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "DTU Breach Fallout: Datatilsynet, NSK Probe Open [2026]",
      "link": "https://news.google.com/rss/articles/CBMieEFVX3lxTE5DLTNVSWt2MWJXZENkOHJadTFQcXBpaG1kQU9CeHZDNEI3WHk5dVZac3hDcWNsdnUzVnVScl9QMzZLcGd0NHRUbkUwUnFMU2xsWFVEX2hyWG50WlB6SVBiX3U1dlprRldRTlFjN005aG11QnRycnczbw?oc=5",
      "source": "tech-insider.org",
      "domain": "tech-insider.org",
      "published": "2026-10-04T08:45:15.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "On Demand | AI Is Expanding Your Attack Surface. Identity Is Where Security Starts. Webinar.",
      "link": "https://news.google.com/rss/articles/CBMizAFBVV95cUxNU3RXRWo2NGpsU2k1YWdXSFZtbnZMTGUtazYwc2xJbWl4N28ycnR3WG5EazlIUWFyOHJRa0dBYnppeFRIZzNUSGIzWnJwN2lUbUFJQzdhTkFjTWtoczdwNl9tR2gyTy1QTGV2QXkzX09BeWl2Y0RMYmU0UTVxNUtrSXNsWWRKclFXbFZfLVlrUk1IUElZSDI4MXNyNXRXcHN5LWpaR1RVbC1nMDZYNkdaOHB3Y3o0S1RtOTlJdUhsSHp3UnlsMnRMM1JxX04?oc=5",
      "source": "BankInfoSecurity",
      "domain": "bankinfosecurity.com",
      "published": "2026-10-04T08:21:20.000Z",
      "category": "AI & Enterprise Tech"
    },
    {
      "title": "Week in review: Researcher breaks into Microsoft analytics service, NetScaler RCE 0-day exploited",
      "link": "https://news.google.com/rss/articles/CBMi1gFBVV95cUxPMF85amVXM1ZJOWVaaWZneGZTYmdERl9nRWp2d013Y3JyczNKU01nTExoM0ZSMzI0em9qTDBVTFRMT1hjQ0EwWC01S1p5MkVMMVBxYzBHZnJGaUZGRnU4OE4yY21XOEVjazFiU3FqNnM3UDFFZ0ZTQW9zcjdTVlE5Vi04UFh2eC12c0M0c0EtcVEta01GdzctWDA1ZTdUZUpzRXlRZl9GVGhiOVRCcjQ0elZidHJua3RmY1Q2NWYyMjBIbHRwR0pkOHFhdXo5cV9iTlV5aXd3?oc=5",
      "source": "Help Net Security",
      "domain": "helpnetsecurity.com",
      "published": "2026-10-04T08:00:19.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "US Ambassador urges stronger cybersecurity, intelligence-sharing systems as Guyana develops data centres",
      "link": "https://news.google.com/rss/articles/CBMi2wFBVV95cUxOMnFZb2dLb3NWXzA5ZmlEY3JPOWx4Q2w3SzJoVHlvZVp6NEN4c2tTMGZnX29RczZRVDJZVUE4TjA3MUFxTTA2Mlh3b0ZIYVFfcHpkT2ZRaTg2T0FsdDlxbVNMcE13anpKZVVvZGw5akc4b1ZDMGVGNVVEWG94eGhrcEhoQnpXRjNwZUJZU1g5OFZZMENBNWE0Z1llTFhtX2JvNExhaExaRFF5cTB0NzZQTllEdHhBYUNXWjR4N1N4SlprZjdtUGxSYUVlTjVnby0yeURUTDFPdzREMU0?oc=5",
      "source": "Guyana Chronicle",
      "domain": "guyanachronicle.com",
      "published": "2026-10-04T08:00:07.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "How Hotels Can Prevent Password Attacks and Protect Guest Information |",
      "link": "https://news.google.com/rss/articles/CBMirwFBVV95cUxQTHhkcjFTeFAtYjRKOEwxWjJJamdMSGZORUpnM3VHUERTVTVFN2dSdUJkeUlDcW5ObFVWMFdpaGJuVkxaUkl4ejdQbE9fYVZRR2ZvVHlEMlVjNERKc21kSGo2dW9lMHA5d0lpM1M3MWNDcHRqZkZCN2xxU2V2NkI5TU5SQ3FEczFRLVpqdVNhQVRqUVhoVW4yQVlaTWNKblhYbGhObmlFZ2p4cm5GRzhR?oc=5",
      "source": "Hotel Technology News",
      "domain": "hoteltechnologynews.com",
      "published": "2026-10-04T07:45:10.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "South Korea orders financial sector security checks after data breaches",
      "link": "https://news.google.com/rss/articles/CBMijAFBVV95cUxOcFl4d2FkNTByX2NzRXVBamtQR0Q5eXdEbEIzQnZNa0F2YlJ1aW1mZEV1V3dNVnVxbkxvLVBHYWw3S0Vza0JfTnFJQWVyaE10MklsVEV5TDMzcU95VF9mMnZsWW9NU1otM2t1TEwwOTdFc01QNmZDUDNEXzhPWllXcU1lS0lwS0pzejB5Rw?oc=5",
      "source": "Yahoo Finance Australia",
      "domain": "au.finance.yahoo.com",
      "published": "2026-10-04T07:22:11.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "ShinyHunters Suspect Rey Reportedly Detained in Jordan, Helping FBI Identify Group Members",
      "link": "https://news.google.com/rss/articles/CBMif0FVX3lxTFBzQmRvdE44dWIyRWxZNVk3UkppOGh6d1dJVXBkVG1RaVhFVjlmV05LaUlCUl9pc0Q2VlJZb0tjQ0p1blY0d1Z3WFJWYjVVSEx5OUFrS2x2TTRabGVPUkUtbnpnb1BQa1R6bjE1SW5VUmN0UlNncDlTbFkxUEhGNlE?oc=5",
      "source": "The Hacker News",
      "domain": "thehackernews.com",
      "published": "2026-10-04T07:22:00.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "China-Aligned TA419 Targets U.S. AI Policy Experts With Microsoft AitM Phishing",
      "link": "https://news.google.com/rss/articles/CBMifEFVX3lxTE9CUWRMckVRQlVUaFRESldPaVBEa3ZkNWlUYjB6eUhYcnNmWFU2X0lGWVR4YzN5UFk5djA4WG40OFozc2V0ZE1FN0xmR011UUtJdlRhT2puQXNsLXI1TU85ZXNQWW56Ry00dGlDR0tCbG8wZGlnUW9uT083QUE?oc=5",
      "source": "The Hacker News",
      "domain": "thehackernews.com",
      "published": "2026-10-04T07:20:00.000Z",
      "category": "AI & Enterprise Tech"
    },
    {
      "title": "Shadow AI Is Already Inside Your Organization",
      "link": "https://news.google.com/rss/articles/CBMijgFBVV95cUxPQWM4RFBTQzRROGx5WW9DZHY1SWFIYzM2eV9RanlIUXhPeHZWZ1VpR3lGMFR0WEgyeXF2cG8xSTFmbUZtb012RUJaRkFvS0hLaDE5d3FZSy1jSlZDa2FldUFVak82LXU5bHEtcmRpYlNtcUJIRjktbzFyNExwMk9pSFFjZ0ZDa04teDJaZkJn?oc=5",
      "source": "Cybersecurity Insiders",
      "domain": "cybersecurity-insiders.com",
      "published": "2026-10-04T07:07:25.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "CVE-2026-9862: Critical OS Command Injection Vulnerability in Fortra BoKS Core Privileged Access Manager Threatens System Security",
      "link": "https://news.google.com/rss/articles/CBMi4wFBVV95cUxNUW9jSXN0Z0k4dGFEeVhyZHQwSV80NjMzN2lROXNFUEJKTHVVLTNuNk1EaWdZYlZtdzVHMFpxMmZUWkd2LW1rM1Nxa25GZXNFNmdkOHdVem5wZFkxWVV5YzVSOGE1NnFlQVZGSjF2YlJWWTVudy1CT2VWcVh6SGI2TFpkV0RWNkZDWms2c0RzZGFBejhYVzhoUEVNZ2dVMFBwRFZ1eVRkT0JVUDUyZk9xRFFkTkpjMklyVFlXMFlWdV9kWV93bEllMnJNMHVONGYtTVY3Vldfc0VoaFd1akRTQ0N4WQ?oc=5",
      "source": "Rescana",
      "domain": "rescana.com",
      "published": "2026-10-04T07:02:58.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "DTUBasen Data Breach at Technical University of Denmark (DTU) Exposes Sensitive Information of 200,000 Users",
      "link": "https://news.google.com/rss/articles/CBMi0AFBVV95cUxPRUU4WXpHT3Jyc3l1MmZnTHpwX2dYcDd4R3BoRmxaRWxpaHRENVJnbkdTcW45c3VSLXI1UExQeko1bWJyODRXRXRkb2tZZGpEOGRXMUhXdUlPbTdfejFtQXNiZmJWb2tmaHBiR0l1ME1YNF82NmJOa0RWdFJkUjlYT3lDcy1nXzV1c2lwbGp4Zllub3c2aU9KeEtaeWpqR21FVzBLSnQ0SWE4Y3BnRXhhRi1MV0NGYlVkcjVrLVlXSjJFNW5DbzFGSzVMam56TlhP?oc=5",
      "source": "Rescana",
      "domain": "rescana.com",
      "published": "2026-10-04T07:02:57.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "South Korean president orders probe into data leaks across financial industry",
      "link": "https://news.google.com/rss/articles/CBMizAFBVV95cUxNU1lNVUVZZ2h4VG9hWTZ3d2lLYk4wX281Nk5LbGpWT0xRWGZKX0I5UWU2bzdNa0xKam9sRjRTREh1QmY2aVRpRlluYzhJQWVjbnZoY3dCcG13dnBtaXU0Z2ZwcGc0dmJiOThqd29QTjMtYmRaa2ZmOHNpVjBPNnV5a0ttMFVLcmk4eWZKTmEtNFBUS1dsNmhrYTJMWk9lMnh2ZFZXYS03NzhIRjQ4Qk5JdG1lTG56TXhjOWlJekZGcVI2MFpjWXd6WlIwYWU?oc=5",
      "source": "reuters.com",
      "domain": "reuters.com",
      "published": "2026-10-04T06:19:00.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "Federal Researchers Ramp Up AI for Faster Clinical Trials",
      "link": "https://news.google.com/rss/articles/CBMinwFBVV95cUxOMkFpc3RjRWZpSWtzMmZIeXlMNk56RHp0TmpXWl9BWUJTSzF1R2tSMzZzRzRpSzczZGJUclkwa0h1RzF5RW9qNFB1T2ZtNV82ak9vMmEybTJzRmhfUk9vNGN0TVlPOEcwb2gwNFF1blhacmptZFZlUWlnbnJFZVlyTEZVb3AxTHppYzl2cmt1TE9pU2pRWjZfdDI0V1pNcjQ?oc=5",
      "source": "BankInfoSecurity",
      "domain": "bankinfosecurity.com",
      "published": "2026-10-04T06:18:28.000Z",
      "category": "AI & Enterprise Tech"
    },
    {
      "title": "Resilience by Design: Are You Scaling AI or Scaling Exposure?",
      "link": "https://news.google.com/rss/articles/CBMilgFBVV95cUxNcEx4RFdlbU1BUVVfUHVXdjdnM3pLRzJWbWxxc3poNXdTdmV2RHQ5RDRDTFg3MkRlUENVSzBlQ3dzeVgxYk1NRVMzT1psOG02SXBGbmNyUnZHWm5Tb0RGTUZTdWZ6T2M5eEpiUkozd1VXclN5Y043b2FFMzdlUWh5SHczMFFFQURjNXlnajJhSW9VaG4xemc?oc=5",
      "source": "OpenGov Asia",
      "domain": "opengovasia.com",
      "published": "2026-10-04T06:16:14.000Z",
      "category": "AI & Enterprise Tech"
    },
    {
      "title": "Beyond vibe coding: Building AI-generated software for enterprise trust",
      "link": "https://news.google.com/rss/articles/CBMiqwFBVV95cUxQZWdPRDdLVlhTQmx6NFVRbmMtUy1LdDVLOHIyWkFBMEJFbHg1VENNckk3cnd3dmhnTlkyeGIyZ2NsN1IzZUNGeEE4Y3ZmYkRrLWc5SlpzaU5mZXJhN1dzN3NKVzMtTjdQWFNfLXZWaG5xbFNPajFIUmNRemtwNkp5a3VucmxzY1F3M1AydkMxLXBVTVdJa2h1c1dLVnViZUZCY3B3TElUMmVHUHM?oc=5",
      "source": "SDxCentral",
      "domain": "sdxcentral.com",
      "published": "2026-10-04T06:14:13.000Z",
      "category": "AI & Enterprise Tech"
    },
    {
      "title": "How AI Is Changing Threat Detection Inside a Petabyte-Scale Security Operation",
      "link": "https://news.google.com/rss/articles/CBMitAFBVV95cUxOR0QxTFdTTERLV2ZUd05yU3dKOHk4VDdyeExGNGdwaTR3aW5KSlhza0JwZE5Zd0M5V1hOVWJlRFNKUU1XQmFDbDRaUjhTRWM0aGVJVFpIdzl0LXAzX1B0ZHJJek5QQU9SMzZNWVF4OXpOcjdFRG55aXByM05DNXl2Y3ZaVGtXUWt0bmRmUmdJU08zSHJ5WnBzMWFaYW0yQTd0YlcyRjc2dFRTOTFvWGFfTm43cXg?oc=5",
      "source": "BBN Times",
      "domain": "bbntimes.com",
      "published": "2026-10-04T06:03:05.000Z",
      "category": "AI & Enterprise Tech"
    },
    {
      "title": "Hyundai Capital Hack Hits 146 Loan Agents in Korea [2026]",
      "link": "https://news.google.com/rss/articles/CBMieEFVX3lxTE1YTkhBVE00VDZaZ1F3ZFNJeVZ3TDd2Vm5ZekFVQTVwcGZXU3JDcjZnSy01anpFb1M2YzhHRE1nSEF3dktwekNSUVNWUjdwVGdwNmxhLWwwelZyRUpfWnNOS2RYcE9ZWkRCeDgydUw2VlFhel9ZTTFHVQ?oc=5",
      "source": "shattered.io",
      "domain": "shattered.io",
      "published": "2026-10-04T05:53:17.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "Oracle Fusion Claw Brings Native AI Agent Orchestration to the ERP Layer",
      "link": "https://news.google.com/rss/articles/CBMimgFBVV95cUxOajNzZklqV2FmZVJjTk1mYWd4Skp0bE1sdXpiN1BTOTNRRExfcl9PWEYydEw1NkhzaXRfN0t1VTR6V1ZzaWhwUjVTR2I0UHdjVTVVRXNZVF9aaGdNWmRnR1hBNExhd3ZrU1F4WHlWdDZTLW5OLVRsNHBNc1NxVkY1ZVhPc0ozQTAwbHJZS2lGci1zSDBSLXN1aHZR?oc=5",
      "source": "forkast.news",
      "domain": "forkast.news",
      "published": "2026-10-04T05:23:00.000Z",
      "category": "AI & Enterprise Tech"
    },
    {
      "title": "Indian enterprises have AI policies, but agents are still overreaching",
      "link": "https://news.google.com/rss/articles/CBMiqwFBVV95cUxPdmtSbWY2d3NRc0doWmZRTi1MRnBvU2lNWHZPY3N2dExOWEpKVFRLYlpzTGdVUnBJZmxHUkYtRmhtdi1hRGJJWWFvMDhFZFVhWFQ2YktHVFotRXhsV3F3MHlfMzN2aXYwMXpzYTVTYUlZblQtZUR2XzlaQThsTkpya1NNRlhYaVhRendWRFdVQnk3cVVNTlR5ZGEzeGFnZ0ZteFlHWGx4SllxNFnSAasBQVVfeXFMT3ZrUm1mNndzUXNHaFpmUU4tTEZwb1NpTVh2T2NzdnRMTlhKSlRUS2Jac0xnVVJwSWZsR1JGLUZobXYtYURiSVlhbzA4RWRVYVhUNmJLR1RaLUV4bFdxdzB5XzMzdml2MDF6c2E1U2FJWW5ULWVEdl85WkE4bE5KcmtTTUZYWGlYUXp3VkRXVUJ5N3FVTU5UeWRhM3hhZ2dGbXhZR1hseEpZcTRZ?oc=5",
      "source": "dqindia.com",
      "domain": "dqindia.com",
      "published": "2026-10-04T05:14:49.000Z",
      "category": "AI & Enterprise Tech"
    },
    {
      "title": "ISF 2026 Cyber and Digital Security Grant: Enhance Cybersecurity in the EU",
      "link": "https://news.google.com/rss/articles/CBMiyAFBVV95cUxNbW5tdFB2RWY0TVVlQmVWQy0tdUtYRmRSaDV4YXF0ZUl3bmprNEtYREVaeDEwdUlyT0pHQUZQaWozYVJMR0JBMk9pemxaaHl1Umo4YlJnNlNmbUR6dVA4YXFsZkhldl9WX0Nodl9Ud2JOU0RsMUJnYk1ZWVhram9aSlV1dVF3TWllU2l4cDYxeHJlRU15Y3dCemNjdWtBMHFjNF9nUUh5dlB6ZUJzSWs3Z0ExT2xlMGFRa1lsalhoTy1zQWh4aWJaQdIBzgFBVV95cUxQcDNsNnFXaWhQNUROZFhQNjl2bkN0RGp5Nncwem9xLTdjY2dHYV9GSDhMWUtZLV8tcWpXN1VYZUZLRWVYbjdlaE4ybXN3cjVObGh1OGY1XzlBX1dGMmg0MjJteWNtWDd1LXFGckt1X0p1OElsY2VFT3NIWGVVZzg4X0lGbUVBS2FPbTJ2bjVGcDRUMFI1WG84T0otcUNUM0ZpTlpEeElpN3BMLWZETlQ0czFVVWFOZHpNanlkZjNwWWhZbE1IbGl1RjJMSFFCQQ?oc=5",
      "source": "fundsforNGOs",
      "domain": "www2.fundsforngos.org",
      "published": "2026-10-04T03:30:40.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "Microsoft Pushes New Exchange V2 Update After Discovering New Security Flaw",
      "link": "https://news.google.com/rss/articles/CBMifEFVX3lxTE5lNXN2S0VDTS11cENtUGJXdEtMUFVDaHRDTXJ1bkVaVGN4Q3BZbm5KbGl0R0lLZmcxdVUwWWFXa0ljV2g1cThzWkJ6MUlXZDQtb01YREUtM1F0d01MYkpaR2hTeVlMdWROWFY3d0JtLUNkNlhoaHhDRmpJaTjSAYIBQVVfeXFMTl82a2pGUHZGTjlTdTZGZjFObGFsRUhxYTQ3dlVOQldESVJjckRwSWhFb0lfbVVsTTUyMGNMMFRSUkNjSkVCeWRDdXQwZ0d4bHlOdk5FMmxCVHpwNkRLR3MzakQtN2RTRGlGLXFxQ0RYZWJSNnZrZFI5cmZ0XzlYSExKZw?oc=5",
      "source": "CyberSecurityNews",
      "domain": "cybersecuritynews.com",
      "published": "2026-10-04T03:06:55.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "Critical GitLab AI Gateway Vulnerability Enables Remote Code Execution Attacks",
      "link": "https://news.google.com/rss/articles/CBMib0FVX3lxTFA4UGJ4VmtVeXVTLUo1dUJMU1Vpb3UySWJKQVVQUDI2YWN2ZmNtaE1jM1RFcjNZbnRNbW0tNFRoTkVYUUM4anZ4aHBJeVRwV2JBcmFlZFVqWXZCcTFjYkpOUVJwUjAxU2pzQXlJUmdpd9IBdEFVX3lxTE4yRjVJalE3OG5lNmhQRTY5YnB4a1pOa2tjT1J3dHA5aHNXWVJQdlQycldHS24zcnNLV3U3OXg0VVp5S3VCU1dKSkxMbHRKV054OGtNb3lmQVNTR0M3QS1LT1VyVUlfYkFqOG4yNTM4OTZQWTZn?oc=5",
      "source": "CyberSecurityNews",
      "domain": "cybersecuritynews.com",
      "published": "2026-10-04T03:06:13.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "As South Korea Tightens AI Security, Agent-to-Agent Handoffs Deserve More Attention",
      "link": "https://news.google.com/rss/articles/CBMiqAFBVV95cUxPbWpQbGJHLWpEV05VZGJpNDRjQld5cFRZOFN4NmpzMGZhd0FleTgzLUZtWWdJQWF5ODIwcEQ3X2NvTWxuNjJqaFYyRlRhLWhXN3Q3NmdhdjVGNlhIdjNHNXdsQnVpdUl0ZGp0c09ITVJHRHU0YktaZFBSQmpoTWkzYk53ZElmaDN1eGZPZGZhODJZMHJ6am14ZmRsRTVmWUVOZHVPYmx4MU0?oc=5",
      "source": "HackerNoon",
      "domain": "hackernoon.com",
      "published": "2026-10-04T03:00:00.000Z",
      "category": "AI & Enterprise Tech"
    },
    {
      "title": "Are the costs of defending cybersecurity starting to outweigh the risks?",
      "link": "https://news.google.com/rss/articles/CBMiygFBVV95cUxQNU5Ncm1yVlNiRVNWS241ZW5YRDJOczE0eHBoTFVhZXJQYXZGRGVDbnI3NkNKVFhqZEphM2h3QjFJUExheVN3dWRjWDJJTFpSM2RVdWs3bmRrMmU5dDhOWkJQMnpRU1l5MUh0T1VNYWtORWdWd29PUGxnZ0YzSjM4TFBoVzBzQW1UZVg4ZzVSWGVZU05NbXdvemhvMlFEbGdWV1Fndm4tRHFVSGl3c2NXMVR2clY3RVlQVlhkSWpZWlhhYXA4c1l1T1Bn?oc=5",
      "source": "In.Comms",
      "domain": "incomms.com",
      "published": "2026-10-04T02:41:17.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "Microsoft Stock And Secure Cloud Names In The US National Security Trade",
      "link": "https://news.google.com/rss/articles/CBMixwFBVV95cUxOVWFSTkpjSEhpS21oeEQwc2U3OFRMMXhMQkRRMUhlaE85MzRlZnRiQjBER2lZM1g0UG9jc2FuZ0FHQ0QycTNnN1BrUlJzdkxPVm81Mm1CUWhRTC1PcVNsaG8yUmxhemlVNjY1VUNieVZSNmFmR3VIbkxxczhrRkp0UWlLU2RvazNEdDFYUDA4Qy16bjEwYmIzN051UUx2bEp6Y1VxeTVSbG1WZWllaXZrZHFtT01hY0MxLVlwMUlVbDl4YXNQYkFn0gHMAUFVX3lxTE9tY2Z1WHBGQU5xQjRreDVsM1R4S3czbm02a0FzbGpnRWZ1ak54N3cyZE1lS09iM0c4TzZIV2xucEViSFIzUFNQTF94c0NHWERfeDdzbnRhSjFzRFUyX1VnZjdPU3N5djZJT3F3ZGoydTR4dlRKUjFfUC1SOVczR1pCRXV2cFJyM3pGUEg4blUtZ2dBTWc1ZVRpOWluVU42WTdYYXBhby1UX3R4WWVJZUpHS2dCLWN1MDlBZnlCZFhldEdRc3A0cmhIaFFxdw?oc=5",
      "source": "Simply Wall Street",
      "domain": "simplywall.st",
      "published": "2026-10-04T02:31:13.000Z",
      "category": "Cloud & Infrastructure"
    },
    {
      "title": "Off-Campus Printing Still Restricted After Cybersecurity Concern",
      "link": "https://news.google.com/rss/articles/CBMimgFBVV95cUxQVmtJT3Q0SS1lbHNLR1Vpd2ZXOTdfUUR5WjJmcG84LVYyTXFIMmdvb2ozR2FRTWFEOTh3cjI5M0JvV2ZFNkJZMGM5ZjEwS20tampMcS1idC05NVNyOXFtSVZkS2FRcTNnNER1YXZNZ0lkSjFiN0psUkM1a3Nwa0ZPOWZ6cmxoMkJEQmtRcThlZmIyUTNpX1k0TGZB?oc=5",
      "source": "theguardsman.com",
      "domain": "theguardsman.com",
      "published": "2026-10-04T02:30:11.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "The Best Personal AI Assistants of 2026",
      "link": "https://news.google.com/rss/articles/CBMiXEFVX3lxTE1wX3BjVHZaOHhlWUVaYlYzdFpjRi1pZzZTbkZWZGVzMC1sTGMzemNJbVE5RDhNWDhGdnJZVTVEQmlaV3QwTUpLUlFYQnBGNjdXbHV3a2FsU0ozWEtT?oc=5",
      "source": "Slack",
      "domain": "slack.com",
      "published": "2026-10-04T01:49:36.000Z",
      "category": "AI & Enterprise Tech"
    },
    {
      "title": "AI enables cyberattacks in minutes, govts top targets: Ransomware attack in defence sector rises 5-fold, vo...",
      "link": "https://news.google.com/rss/articles/CBMitwFBVV95cUxQMHNjTFJXTEl5LVRxUktiRkVMcG9FMDhDMG1FRE53N25KU3YxWlIxLWdyUDZ0c3FDUVdaVDBmV0h5aXhtWTlFUzVoVWFxRklxNVoyOFVvQVF5eFVEb3lvN1NUS0U4X1RvclExb0ZoT1ZkVm1JTkJvRV93Z0k3UTBnSi1nU1NtMFprNkZ5Ym1HM2JZZFVYX1pWNWM4WXVjR1dZajB0a1dVVG1qaUREYkd3SXZ3eE1LY1HSAbwBQVVfeXFMT0RnQmU4X2RweGxQNVY4MTBNSEwyUUtmUnItRzNVdW1OWEVoanhBY3g5RnV0RER1RGFsQkEwRkFWWlBuMzVPalhYWGlNUGV0MmVJSmdibXEwWncwR0ZLdW11dkhsdTU1Sm9vM1dhM2JTT1BnSTZHRVlmUUhtWkNMUlRETUsyeVUybVBIY2tNd3JWTTRYZG1sOWlKSGx0SHBndVptS1ZEVUZINkJoNUE2bXdaVjl4b3Z2ZnRxZng?oc=5",
      "source": "Bhaskar English",
      "domain": "bhaskarenglish.in",
      "published": "2026-10-04T01:14:32.000Z",
      "category": "Ransomware"
    },
    {
      "title": "AI Security Surge Fuels CrowdStrike, Palo Alto",
      "link": "https://news.google.com/rss/articles/CBMizAFBVV95cUxPeVJXdndHZzVBdTZsTlAxd0hya3FXaUpULTJ6OTJIN0ZpV1hHc0YxaW9BU0JzRVB6eEJNNTVKaXhocW4zRzJOYlFTalJzRnBRWEx5MUlEdWR6OW5YanZsT0tGQ0hLRXVnajlOSFI4STFub08yQm5pTmRreGdTcTFPcVR3dzlENGlQdGdmNXRGZWJiZTlLOXVvYV9xSkRvOFBPNklZV0FuWTVzMnBIMUZoaUlTZ1JFNXJ6UG5meUlkWDdUbVlNcE5LeHRxTlM?oc=5",
      "source": "saasrise.com",
      "domain": "saasrise.com",
      "published": "2026-10-04T00:00:46.000Z",
      "category": "AI & Enterprise Tech"
    },
    {
      "title": "South African companies that are hacked pay an average of R5.01 million in ransom",
      "link": "https://news.google.com/rss/articles/CBMixAFBVV95cUxOZ3RHdTR6ZnBMdy1UcERJY29feVJheFVIc24xNzBTcmo3YnZmaDFicXExb3ZvczNlRmlXZVVrUnJaemY0TWtfUTE2ZF9DVXBTMFVFb1FxMDZoWE5reENhS29yNkFNdWF1X3NZS1pZRDU2UUw2Z2tyZmJYM3M0MlQ5TFJPLXdvSzRBNjNMM2dCalFZOGxaaW54RzdoS3VoWVgtcGU2dThRZjdhdTU5a0pIY2ZObTdjQXJmQmw1bEtZUnlHckFE?oc=5",
      "source": "Daily Investor",
      "domain": "dailyinvestor.com",
      "published": "2026-10-03T20:11:59.000Z",
      "category": "Ransomware"
    },
    {
      "title": "Umniah by Beyon Brings Healthcare Leaders Together to Strengthen Cyber Readiness and Resilience",
      "link": "https://news.google.com/rss/articles/CBMiU0FVX3lxTE9iNk9DaWpCajRGQUgxSms3SUJpZzh2QklwRkhuV09jSVZ1VEZzamY5TXVLTDlQNW10Q3FWRmVOa180dXZqRUFfczhzSnFpazdubjRJ?oc=5",
      "source": "جهينة نيوز",
      "domain": "johinanews.com",
      "published": "2026-10-03T19:37:32.000Z",
      "category": "Cloud & Infrastructure"
    },
    {
      "title": "Cybersecurity Awareness Month with Commonwealth Credit Union",
      "link": "https://news.google.com/rss/articles/CBMitAFBVV95cUxNMmNNQVhrTTJvUFhSUGFMeTQ4a0wzOUhLZnpzYUI4dmhRenNuSnNsLWI0NGd5dWRxS2FSN0dPOTF3NHNuX3VTRHhXcDZJODBaTDhVYkdNSW9BTFJXOWJfVHdQOGFSUDNDWm5kU244YlBRRXNDRjkyWGwxYWFzek1IV3V3b3dIYVVoeGEtNGVWR2FnVVlWMTB5a2RoR3Q1aUM1cU8xY3dnUFhSUUw2Umh2MzB4bUc?oc=5",
      "source": "LEX 18 News",
      "domain": "lex18.com",
      "published": "2026-10-03T19:21:12.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "How To Price An AI Agent So Procurement Doesn't Kill The Deal",
      "link": "https://news.google.com/rss/articles/CBMikgFBVV95cUxPTEZNaHZyX3FGbXpCV2o1Z3o0WTlOcHh1SmZLRFVORTBiN24tbTkxbXVJbzJLNTdNLWREeEJhOXFEX3lEY1ZzakFEbHoxNHdhdjIxbll1YWFFME1idlhTX29kZEF3eFJ5bWVELW5pb1ZsZjNrMkJkNW9vdEZIa252UzhtYklxZ2lEMGpWSFRhY0ZTdw?oc=5",
      "source": "Startup Fortune",
      "domain": "startupfortune.com",
      "published": "2026-10-03T17:03:18.000Z",
      "category": "AI & Enterprise Tech"
    },
    {
      "title": "Nvidia unveils security platform to stop AI agents from going rogue",
      "link": "https://news.google.com/rss/articles/CBMirgFBVV95cUxPekloMU52Y0FGSHF3VmpLTS1xaHJWVm13eHR2b1ZCM1NMaWFKSWhNdWF2THRPVVgyRGpmbTFTaGRYY2pydTlWYng2SkxqTjh0MkplMktIWENvZlp2dFdzMDhDTl83a0c0QzZfT19ndlRVa0FZTXdFa1Zsd0x4T3lNenNqZjRIa240T0ZGSWhfTUpiX25CcWNxUEZ2MFI5RXg2U0dYU3BocFNrbWt6b1E?oc=5",
      "source": "wccbcharlotte.com",
      "domain": "wccbcharlotte.com",
      "published": "2026-10-03T16:55:04.000Z",
      "category": "AI & Enterprise Tech"
    },
    {
      "title": "Epic pauses product development amid cybersecurity concerns",
      "link": "https://news.google.com/rss/articles/CBMikwFBVV95cUxPeTY3OHdZXzBoRV85dmRsX2FUTFZYM1lLcUZEc0owTS02NExVMHhQbnlDdEYxMFppUmk1ZmQzQkJrZmR5cFFVeVIxeFIzM2pCY05Sb1A4SjFkcWNyVlZuZjQ2RDdLa0tnUU44VGdPSTlCYlRDSDFpYUdPSzUtNElOVmJ0SEppeG5WVGdmQkRrZDlRNVU?oc=5",
      "source": "SC Media",
      "domain": "scworld.com",
      "published": "2026-10-03T16:42:51.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "GitLab warns of critical AI Gateway vulnerability allowing command execution",
      "link": "https://news.google.com/rss/articles/CBMiqgFBVV95cUxQTWtkcVFfVDFIZ01qM3FfT1ExbG1KR18xMVZMSFJUcWxsMjVJOTRTZkdOeW1sTlJwQVJWY3hPV0dXUFhrd0tPN0plU3BPZlhub0hkUjE2MTVZd1RSbnhtS09WaTF6dmVRelFuTjR1dXV3N0tQVHRqX0VEdUdPSExaX1lyUUxkbzB0UGdOWmJOY1VPeTJncmp4RXpjUE11dmozOHpQY1REV2paZw?oc=5",
      "source": "SC Media",
      "domain": "scworld.com",
      "published": "2026-10-03T16:33:43.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "Tech Valley Cybersecurity Symposium returns to Schenectady",
      "link": "https://news.google.com/rss/articles/CBMikAFBVV95cUxQX3BQTW9xNmhHbW13Nktrb0x6ZkpQVVB6TEVrYTdOUGVIOUg4WlNoYXhuTVJaM2lwQ2dDSEgyWTUtUWxxUFJmYXVlM0pOUmRudUhXT3NvRU1CWHA1WnlxVnM4OWdCaWtjY3d2cWU4N3Z4b1ZyT3pCUTJWNHNVc0NoRHRaNFNTRWp3bmRwM3Q2clnSAZYBQVVfeXFMT3FtYXhhY0lwLUpWNEdoQWlSYTN2aFZIMEJBOHYyMDJQc3FfZURPdWxpUGdFZFBobnNvZkhIUGVxOE5qU1RyTExYVHd6Y1gzcFNnVWxsWDJXOFVQNXAyOENMSThRME1MdmtlQXVwWl9hUy1nMmQwV01yWFcwZXhlc3VZa2tvYUloRUhQM0hjNktSOEthdHpB?oc=5",
      "source": "NEWS10 ABC",
      "domain": "news10.com",
      "published": "2026-10-03T16:12:36.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "Stay on top of cybersecurity concerns during awareness month",
      "link": "https://news.google.com/rss/articles/CBMimAFBVV95cUxPd0t1elQ2NV95d0RaMDlOUVRsSzFWUzNNOWFCYk5jNm5UY1FkVDFCSU5lMnQ0c2lNV2xXMnVNSDA4c0NTNHhpTlF3NGVYdlRXWlpfNlp4QnhrOHBXYlFBOWR5OTQ4Y1hXVG4tRncxRUdjQ2NNT2RsWE5uOUJobG5pV0lYWDhHbmlUSGRieHotYXBJQUs0U19VUg?oc=5",
      "source": "Chattanooga Times Free Press",
      "domain": "timesfreepress.com",
      "published": "2026-10-03T16:00:00.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "AI agents just doubled inside the enterprise. Confidence rose faster than control did",
      "link": "https://news.google.com/rss/articles/CBMiwwFBVV95cUxPOFdlZ2J6R0MydjAzYVJFTkZ2cjZ1WnpzVGNQWFpBUXNTZWpjYW5XZGE5UkdDaHlaMW9BUmx5dENNZXdjSUJFbGZoWlJXd0kxeGYxZFNyNUo0MmwxM1hvbDNTZ2J1YkZ2bDFvUHhmY3BRRE1Td1p5MnZKMGZ1ZTd1dmF2Q1VCaEJPbmVhUk5qMGNFblJyMXJONXktMHIzcUM3SkRmbFBWUHR4cWNfWU9wa2FwcjZKQy00NVlVRjVKZ1JiYWM?oc=5",
      "source": "TechCrunch",
      "domain": "techcrunch.com",
      "published": "2026-10-03T14:00:00.000Z",
      "category": "AI & Enterprise Tech"
    },
    {
      "title": "SA’s ransomware problem is hiding a much bigger question",
      "link": "https://news.google.com/rss/articles/CBMirAFBVV95cUxOMjcwQ2VIOW1IZXlHR3FWSzcxX0MyWXF1MDFlV1lwbU91M0ZjR3lITjNPcUZyX3JZS3pNbTE3ZUFFUDlvS29hVXQ4REZLYWdvaU0yRFFIeFQyekNGVTA0S0VOZGtoM2R6cFl6MWhOWjd2YW5oN2lYeVNXbVJYb2R0cUxadTNlTS1aMjE0Q2hxbzFvS0ZNdW00UktSaFlOOGdHcVZkY294azJURjRt?oc=5",
      "source": "Daily Maverick",
      "domain": "dailymaverick.co.za",
      "published": "2026-10-03T13:41:44.000Z",
      "category": "Ransomware"
    },
    {
      "title": "SK Shieldus Becomes First South Korean Company to Earn AWS Threat Detection and Response Competency",
      "link": "https://news.google.com/rss/articles/CBMidkFVX3lxTE5ld095MUo0aUFFSmctbWt6NWJ4Wm42bGtGRUtqVEk2bFBsMDRqWHk2cjB3ME9DVUdZbjhoNjNxLWZpXzNBaGNyb0drYTBWQzMzVVdpeTNmbGpuUHVuT2F1RzRwXzRhTVJVSGpJV3l4d3J3M1d2eGc?oc=5",
      "source": "finance.biggo.com",
      "domain": "finance.biggo.com",
      "published": "2026-10-03T13:35:00.000Z",
      "category": "Cloud & Infrastructure"
    },
    {
      "title": "Dutch Institute for Vulnerability Disclosure Breached via Zammad 0-Days",
      "link": "https://news.google.com/rss/articles/CBMiiwFBVV95cUxOVDY5TEpDWUxsSDd3WXZIRmM1LVhUQWJyUnRoc0pBU3kxYWg3OWo0eXJmU3ZwYWt0S19SR1NEXzJzdmpWZUx0YUlfajNyYnVjTEpMcjhIUHp4OEp5WklYcTF0czVmMFV2bWhyNnJGRU9GbjR4MG5QS0NieXRWQVJsTUdYRFRGeTlJM0k4?oc=5",
      "source": "hackread.com",
      "domain": "hackread.com",
      "published": "2026-10-03T12:00:04.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "The State of Cybersecurity in 2026: Key Segments, Insights, and Innovations",
      "link": "https://news.google.com/rss/articles/CBMiggFBVV95cUxOVllIVUxxLW41SmdMNzRhdHhFWWUyNGxrSF8yRkltT292VXNrSVlrYm1YelNER2pvZzZSYU5OSW9TVHBJMEd6ZDNvVWRvdnlsZGxVVUNsYmZnc2NKNzZDanRCZVBoZ01hUjNMZjQ2RnRJWkd4Zk5tSzBOTGszck15TWh3?oc=5",
      "source": "The Hacker News",
      "domain": "thehackernews.com",
      "published": "2026-10-03T11:00:00.000Z",
      "category": "Cybersecurity"
    },
    {
      "title": "CISA Sets Out CVE ‘Quality Era’ Framework",
      "link": "https://news.google.com/rss/articles/CBMioAFBVV95cUxPZnFIT25PSXNwS3NBTC0zM1lYekNrVFhRU2l5ZDNXbktrenN6Z2k5QktCY3g3VlhzblJuV1RnWDVjdWZTVUdwQ19mQVRqTUVPRzZUT04tUzdxYnozb0ZMeWd6WDM2SDRFNzNPLTNsXzhLeWg1dzFPb3hJcGlENDNuMWVpTk4ta2tXdXFMZGxpUC0wVzVzeWJKck8yZVdWMERq?oc=5",
      "source": "LinkedIn",
      "domain": "linkedin.com",
      "published": "2026-10-03T09:00:23.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "Ransomware Harms and the Victim Experience",
      "link": "https://news.google.com/rss/articles/CBMinAFBVV95cUxPMjFhbTFlSXlMTE9xSzF1RHVwa0kyVDBYZm9xbHBUWnB3X2gtRzhYUWJOVHBQNE93WnNWVEpmRVhYY21STlRVUGZiYy1UY2UxN2JqZTc4UWk5MEtfa2lMQkxxZFIyZERsdm9tTVlCZGZhT19ya0Q3aDRPNHRJZHhxRlpyWEdNZnJKQ1huU0FwSkxaSGZfcUhfVTZzSks?oc=5",
      "source": "rusi.org",
      "domain": "rusi.org",
      "published": "2026-10-03T07:53:26.000Z",
      "category": "Ransomware"
    },
    {
      "title": "Iraq inks data center MoU with Huawei as tech giant employs 10,000 across country",
      "link": "https://news.google.com/rss/articles/CBMimgFBVV95cUxQS29vNFpSd3VlRmY1N2plN2FzdzZBaFY3WEhpRzRNby13enNtaXZoeHhxVm5XV1Jsb1o1NXVRV2c2VmtodUFWeEU2YlJpU08wRzExejdtSXlWZENnNEk4aFpmcnVLZFJVdnBZbnQwQjI4WDlKcUlvZE9kdk53MENuOGlwU0ZPWjJIbVpHR2U0cmpDVUREREtkVmZR?oc=5",
      "source": "IraqiNews",
      "domain": "iraqinews.com",
      "published": "2026-10-03T07:11:58.000Z",
      "category": "Cloud & Infrastructure"
    },
    {
      "title": "Amazon investing in data center host cities",
      "link": "https://news.google.com/rss/articles/CBMikAFBVV95cUxPWE9DRjkzb1AtdVZUMEVSRkNQaGdVOWJvcmF2NWxrTUk3aWVkekoxbG9DVkswN2RMTWFwT3R4ejlFcEUtRjJUWldSSDlRRk9ONjdsOGQ0SUpXNjFNSzRoUlJPdWVIUk1zOFJmVkVncUE5M1dmOGRiaEhXTzdSVHg0MDBCV0NWaUc0STdLT3pVN3k?oc=5",
      "source": "nwaonline.com",
      "domain": "nwaonline.com",
      "published": "2026-10-03T06:43:00.000Z",
      "category": "Cloud & Infrastructure"
    },
    {
      "title": "Ransomware attack paralyzes Japan's largest rail operator",
      "link": "https://news.google.com/rss/articles/CBMirAFBVV95cUxQVndXdWFLRF9xWkx5YWdjZGRPMTJucUpGNEpnTTJRRDZ3U3FxY09jQmdDVUl6ZGpmYnh0LWM3WFhMLV9DMm9zRXNmT255ZU0ycmo2NFB0YkV3anE3bkp0elowa180bE8xZGZIZFM2dzJiMlBPZlZCSDZSYnhqMG1GN0lxM0ZSMWJ6ZkFxelQ0X2ZnQjVKMm1Xa2N6TjZRTFNoX1d0cjVFdVFkTzBk?oc=5",
      "source": "Escudo Digital",
      "domain": "escudodigital.com",
      "published": "2026-10-03T05:20:01.000Z",
      "category": "Ransomware"
    },
    {
      "title": "U.S. CISA adds Zammad GmbH Zammad flaws to its Known Exploited Vulnerabilities catalog",
      "link": "https://news.google.com/rss/articles/CBMizwFBVV95cUxNZ2hqYjJKTEh0cmJ4OGZsTThadjgyYlItTF9RZzJPc290UWc5YkV5N3hDMUdDX1RGNlBKWjNnQmJrU3pzYVBoQks3dTQ5Yll0R29iang4cTVHSkJHLUpiOVc4c2RBcWg5dVFhTFBhZHlza3YtSTFuUldEZVlnV3liNkJGTHEzUW54anJ3dGJ4SEFrVHY5aUhrMVNKZlBid2dKR2F4VkFoSTd1bk9MN1g2M1AtYzdhcXB6UkR6Q0x4Q0JOZU5SSHJ2NHEzc3lvZUHSAdQBQVVfeXFMTzhvSW1RR3lGSjBnN1VjM1hVZEw4Xy00X0d1OHFNZHVyWTJtOXJKelVWazhtTGxjclZsVTR1ZGN5cjVLT0pnbXpjbHNmVDZad2VFdmt2cEEtMXVlUWJyQTZnT3R3OXJZVFJpY1FYU2pOd3dNWno0dE5uWEVxN0FiN1lURmNRSWlpMkNzN3ByUHYxdk0yTk04WXlEZ2RKTkN0LU8zYWk5d2Z0VDFTMFVNdDBoUWNWTXFKNUFGS0Uza19GdWx2LUhxY2Ywb3RkYU9YOUtZZTA?oc=5",
      "source": "Security Affairs",
      "domain": "securityaffairs.com",
      "published": "2026-10-03T01:29:57.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "Marin County residents concerned after report reveals Flock cameras data breach",
      "link": "https://news.google.com/rss/articles/CBMijAFBVV95cUxPaS00UUxwU3Eyb2ZTVTdQNC15YTdHa3F1VHRUQVpPMGM2Mi15VHRPNXRwRXVQejhSRTBnTy1mRlFjdmkzOEViSW9QcGw2eFhqNmRxMWVOdnNYdTVpeHFlZEsyNUhzT0FKNjhNOWI4Tk9uU3d6aUkyTUxXM3FyQURKYkRXTW15dndJRzNQTtIBlAFBVV95cUxOb3RUajE0dkhvajhxN2x3WnVwa1NhNlhjQV91TGtVV0hTX29DWHNDNjNNekdIV3I5VGZoNElQd0JsQW05ajRuZHFnTVFwU2ZhNExpdEYwQkd2T0JqSFhBME5MX2p5OVJHOGpyWVVMQ1ZOaXVEZmdkNHcwRWQ1aHJwMGtEcER0NElZUHNXMmo5bFJ3OGlm?oc=5",
      "source": "NBC Bay Area",
      "domain": "nbcbayarea.com",
      "published": "2026-10-03T01:13:18.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "Poppins Payroll Data Breach Investigation: Edelson Lechtzin LLP Probes Class Action Claims After Customer Data Is Exposed",
      "link": "https://news.google.com/rss/articles/CBMihwJBVV95cUxQa0NZZUtnb2J2TmVmWUZvTFo2Z0VWQlo1c01pdTdUaXpMWnBVZW5KRFhYU2pEcFBYXy1hVFdnZ1dpaXU3S0dmR1lEZGN2LUJyVnZ1c0N0NEhRbDAwbVRFNS1pOGRCWjA2djlEOGp0NjVuR1RzSkZ5YUJzMEdEdk9aUW9GZWozNF82M2JGTFNQcXV1MXNXWVRFS29Sdkg2LTk5RWFfY1BMZHpOMmlEcS1FYmFxM3NSbXdfb2x6U1llUW91a3ptVXZScnZQbXE5UGh3NUZMM2RKWk8yTGJLXzRQZ041X19lVzlDbFluS0FMYmpjZU9UelpNVGF5eXRiX2RFSGExekJISQ?oc=5",
      "source": "PR Newswire",
      "domain": "prnewswire.com",
      "published": "2026-10-03T00:52:00.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "AuditTeam Targets Ad***ng in Latest Ransomware Attack",
      "link": "https://news.google.com/rss/articles/CBMif0FVX3lxTE5ETWtDczgtdmZtLXViM3RaQW9MVkt0bTgtM2dIUlZZaU5ycXM4Z0lrY2pxWElvOWQxeEwwOTJiVUFqbkczdUktMVRiQVFRbDc3VXdVb3k4UnI2a3pZRkdCM3pFRnJOcWZOY1dqOFBfTDZ6a09xY2NFSjRXRDd2eTA?oc=5",
      "source": "DeXpose",
      "domain": "dexpose.io",
      "published": "2026-10-03T00:00:00.000Z",
      "category": "Ransomware"
    },
    {
      "title": "Latvian State Forests blames miscommunication for recent cyber attack / Article",
      "link": "https://news.google.com/rss/articles/CBMiygFBVV95cUxQNWx4TFJ2WUN2LURsSUVPdjNNclNwSUdHeFo0ZkZUN3dWNkRJQzZYRHdKUnBSWlBjanZBM1pzM2ZDWEdLbGVELUhNSEZmV0Q5aHJzaF9CMzVWY2F0UGJnX3hjMEJ3TGxZcU40YTRzWHZnN2o1Z3REQ3pYMFVpY2djNjJWWUktUzF6U21hNXZPQ0pXeXFaeEl1WUU1NTFndk1wcS0wMEo4Qk5PSWEtcWdieW1FYW1Ha1kyWFMtMGdjeG9aQWRYVklGVE5R?oc=5",
      "source": "LSM",
      "domain": "eng.lsm.lv",
      "published": "2026-10-02T23:36:06.000Z",
      "category": "Ransomware"
    },
    {
      "title": "Vicksburg impacted by ransomware attack",
      "link": "https://news.google.com/rss/articles/CBMiggFBVV95cUxOdjZBeW8yQWd1bzVMTFFCUzlETmQtUzEtUnRGSXdiOWdzdTFlS242TjZDcHFfXzBuVkxxTEhRZFNkWGRjU01UR0lnQXdqcV9XQlZtY1dqM0dTLXVPbm1fT0RNb0tteUNLWUlFcXU2bHlndXh2aXdONUlLd0JhNDlvWW1n?oc=5",
      "source": "WJTV",
      "domain": "wjtv.com",
      "published": "2026-10-02T22:07:06.000Z",
      "category": "Ransomware"
    },
    {
      "title": "City works to restore systems after cyberattack",
      "link": "https://news.google.com/rss/articles/CBMiiwFBVV95cUxQUG1MWFdiaFlBTGZQd3VXRjQ3UGlYQ0N5TlNQdHRuTGlpaDQwS2JmZHpzb0JvR1lfd0E3dE56VkVIOWUyU2tDd1U0ekxpMldlZGVXM1dpNFJ3cUVvUzJ1SXNnNWp1MFVKZDFvSzFXU1MyNllnSTNaMXBmVTdQcTFicVFvdVotb2pHYkVJ?oc=5",
      "source": "Vicksburg Post",
      "domain": "vicksburgpost.com",
      "published": "2026-10-02T20:13:29.000Z",
      "category": "Ransomware"
    },
    {
      "title": "AI is Critical Infrastructure: Securing the Foundation of the Global Future",
      "link": "https://news.google.com/rss/articles/CBMiswFBVV95cUxNM0NkWmlyR1BwZ1RpSDFjOWlpYjd6UTZQYzU5VElVc3JYalJRV2twVHJtTmV3eXNoWGhuYWVGQ0xTdGpxQTJLNUhPYTYxS1RMWXpXRHhIamllWHNndllKbFZRcjI0cG41NzJBTmk0aFBiSUtUYWhMY3YzMzJBdDVVT1JTbzB5cm5PRFJrZWpYU21pc3pUZGxQbzZocGpqZ0dpalg2VVRnR0NJSWxmTUZ4c1BBZw?oc=5",
      "source": "Security Boulevard",
      "domain": "securityboulevard.com",
      "published": "2026-10-02T20:05:13.000Z",
      "category": "Cloud & Infrastructure"
    },
    {
      "title": "Frontline Education breach exposes school district employee data",
      "link": "https://news.google.com/rss/articles/CBMiswFBVV95cUxObm45WmRoQmFESElDTU5XOTBiNUFSMUFXZnFIdVc1VDNoSFhwSERpUXZTS2Z4Q3U2Y0FQa0t5S2oyMnRqUHdvNjhscFRzMjdPaWZrU29JYzJSanRCNE5DeHptSkpDa3p4WHpjcHFiSUdwUXZGTUU3am9CVkEtVGg0ZHFnSjUyWkFlQmJSM2lGZ0VOT09DMXpmQnZsN2pDb3Jkel9OcXdCVG83MzdLZ002M2J4a9IBuAFBVV95cUxQV1U0ZFZxVmY2dzJEcEZ4eVlUU3VjblZ4UFRWUUl0VDVWdmpzXzNKR0ZUWnAzSjdIeFVHVG1YaklYc3VhSXR2MHRUNzBZNHdFeFdEOEthdEVydHMwemttZGVEbTM0YlRSZEU5S0g4bWJueXF4Q1NITHEyd2dQNzY3dnRaaXgtZC1EbEVZWjh6MzZFcGZySmhhU1FGX1V5MGFIejZ6YUhtdTB1OXJOYlR0MEFEb01uMmI5?oc=5",
      "source": "BleepingComputer",
      "domain": "bleepingcomputer.com",
      "published": "2026-10-02T19:01:40.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "DriveWealth Data Breach Exposes SSNs; Affects Millions",
      "link": "https://news.google.com/rss/articles/CBMigAFBVV95cUxPLUhJVXB5NmNlN1RzS2MtNGpVMHZYMDliMW1zak1MMGI3WFlCUmNxWFFFVmZCckVTM2FsbzNlT2h4R2psM2ZrbzBYNUdTT0VGR2REUFl2RWotb2lFM0R4bUpXakNSakZVNl9vYmQ4Q1UtMTlIQU9hSVRRdzB1dTU3UA?oc=5",
      "source": "classaction.org",
      "domain": "classaction.org",
      "published": "2026-10-02T18:46:02.000Z",
      "category": "Data Breaches"
    },
    {
      "title": "77 GPU Clouds. Only 19 Medals. | ClusterMAX 3.0｜Latent Space",
      "link": "https://news.google.com/rss/articles/CBMiX0FVX3lxTE9uYkk1RzFuRjFQSEplRG1kVzFkSVJNNnNaNW1jVzU1Vm9YWHdxQ0hPWUt0NWJfb2lkYk1POFdQX29ZLWEwTWlFQW5xMGdhQld2SVZLR3hSN0RBR0c2elhR?oc=5",
      "source": "finance.biggo.com",
      "domain": "finance.biggo.com",
      "published": "2026-10-02T18:43:56.000Z",
      "category": "Cloud & Infrastructure"
    },
    {
      "title": "Warlock ransomware breach SharePoint in water, telecom operator attacks",
      "link": "https://news.google.com/rss/articles/CBMiugFBVV95cUxPVGVmSFh6WG0tc2Z1c1M1MXFvdHo4TnBnaGFuSmpXeklkSWlOQUh6OWpOQ2k4X1hHQWstUUU5ZTkyWklRVWJ6U0JNMnpPa2NOWDJXZlBPcjlTcVEtMlRtY00tMnFSZThreTE2Tzc4ZkNsdU1NUVBKRmVOYnFWS2hfNk1oT2RLWXRxTU5rTnJtc1F1ODA0RnFKQlNkVVpWWE9HVTB0N01qNG9VdXRZU2c3bUV0U1JpWW91alHSAb8BQVVfeXFMUEJLdEhxRFJ1UFBmZE1vT1hQbXlSX3pLMU5OZTJwQkc3SExVM29sdTRHV1ZaR3ltcEp6Y2JLRTFyU3c0a2d3cEJ1UzAyc1BWNkRxYnl4Z1JSSWVIMGtWS19Qb0txck92aVBkRExoVEYzSUFPRDVuUWhweHJWakUwZjBTT2JMVVhJTTVpSG1NZEtYZkZvSUc3U00yamxMUmQ0TmNtb21MQWhleXA2ZE51NTlOSUN6YzNDaWQwNG5vYTQ?oc=5",
      "source": "BleepingComputer",
      "domain": "bleepingcomputer.com",
      "published": "2026-10-02T18:33:01.000Z",
      "category": "Ransomware"
    },
    {
      "title": "Ransomware attack disrupts some city services in Vicksburg",
      "link": "https://news.google.com/rss/articles/CBMijAFBVV95cUxPcjUtYUFEUk1fRlVuTVoxOXFtcHZ0alg1MjZvSDFvZnhiZmI1R0t5Z2Z2X2NLbjliSXkxM05sLUJVdy1HRlVnWmU5LXdidEtsbWt3VU80XzN5RHhFd3F0MFdFM1hXM2FNcjQxSkg5aE54c0FVcFhDTHUtRzBudHN6WXM0cVBmczk5SWpKLQ?oc=5",
      "source": "SuperTalk Mississippi Media",
      "domain": "supertalk.fm",
      "published": "2026-10-02T18:25:12.000Z",
      "category": "Ransomware"
    },
    {
      "title": "What Is Behind HPE (NYSE:HPE) and S&P 500 Networking?",
      "link": "https://news.google.com/rss/articles/CBMimgFBVV95cUxNRzFYUlpMN0NPZm5pNi1yOVZlQ0k1NFBpT3pubEplUXVwOU5wVlY5MzdnNHhtRlVRaTFLYllrVjJZUGJhLVFmSzd1MjRBdmxGY2tiOVBTdzMwQUJvYUpOdGtGOEZEMnR5T1Zpam1kRkNoOVpkSzR6NkJGZnJuZnFORU9jWVg2UFVQVGRQQ1k4Ykc2R1VIZ3dkdU5n?oc=5",
      "source": "Kalkine Media",
      "domain": "kalkinemedia.com",
      "published": "2026-10-02T17:26:00.000Z",
      "category": "Cloud & Infrastructure"
    },
    {
      "title": "Dylan Patel: GPU Access for AI Startups Is the Hardest Ever as Inference Margins Hit 60%",
      "link": "https://news.google.com/rss/articles/CBMiW0FVX3lxTFBhLTVmUXMySFhQdGlPUlhhX0RCOU4wNllhbWtteDJCUDg5RHE0ZERjTzdGTUdxTUc5YndOaUVSSjhkNDZLUm1jY082NE4yMFRUZEFvU1BXV0tvZW8?oc=5",
      "source": "finance.biggo.com",
      "domain": "finance.biggo.com",
      "published": "2026-10-02T17:08:00.000Z",
      "category": "Cloud & Infrastructure"
    },
    {
      "title": "Dell CSM Flaws Enable Unauthenticated Admin Access and Root on Kubernetes Nodes",
      "link": "https://news.google.com/rss/articles/CBMiggFBVV95cUxOcTFGdDlkaV94QW9zX3psbl9wTktqNlZpR214UjB0RVVoa1M0TVdGX09kYS1xeGRwdTI5OFB0X3podmJRWnFFc3haenVpeVdaXzFXLXdEMUVDdjNQZTJWMDBINU5sT1FId2Y5U0hyLTN1ZlN2cjRtYWQ4bnNOdldVcWlB?oc=5",
      "source": "The Hacker News",
      "domain": "thehackernews.com",
      "published": "2026-10-02T17:02:00.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "GitLab warns of critical RCE vulnerability in AI Gateway service",
      "link": "https://news.google.com/rss/articles/CBMisgFBVV95cUxNd2xlYjZ2SEYwa29YaGV1akZtRjJrbmNDbEVpY3p3b3BOX3UyMUkxbnQ2TldjWk5zU3VVTkZyVkNIdTlXeWduUTN6SG9aY3EzRi1IZG5OYkVBbGJ3WE5xRHZTdGllTFNGX0EwWlZnNGRCWWR2eHZrZi1oa3YxV1JBZHVIbDFEdThEM29ucUJyNVhRa2EtWnlBNFlXcEtvaGxEV2pzSjFlWXBIMUVkdTRTOVhn0gG3AUFVX3lxTE41aV92SW8xZkhxa2JjNGNnc1dTSmJpVlViVmVST0FPVEI4Nm5BV0dGMjlKeExIYUR4dlBkT19qZmF0LWk4SEl2bWpKOE82dVZvOWZSWFFTcTdKbG5YMWNLa3lkWFpWaXVlQS0xOTN3NDdYWExndXFVS2doZnBPZkg0TUJaQ1R3Vy1aeFRqZzdhYThHLVNBYkxNem9uZ1VFa2xsR0RjeVhSX1hpbFVNekJINnBVeG5tSQ?oc=5",
      "source": "BleepingComputer",
      "domain": "bleepingcomputer.com",
      "published": "2026-10-02T16:20:05.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "Google Says AI Is Accelerating Vulnerability Discovery",
      "link": "https://news.google.com/rss/articles/CBMic0FVX3lxTE1XSU1yb2FwM2tpQWtSQkx2em5ZODFJRDdqMmEtUXNRVlZkTVhfcVNlNmhNNU94YVhrRUJUT244WlQyaTNJYTlTcEVhLXI4cDZ0UFd1NFdSRE9IWVlIeE5lME9fUEFSQ2xEX3FaQlpKYmdxVmM?oc=5",
      "source": "Petri IT Knowledgebase",
      "domain": "petri.com",
      "published": "2026-10-02T14:41:34.000Z",
      "category": "Vulnerabilities"
    },
    {
      "title": "Family Physicians in Jackson Township reports data breach",
      "link": "https://news.google.com/rss/articles/CBMitwFBVV95cUxORTRhREdCOS14eG9nU1M3SlFEQ2hidE9RaE5UZjY5T05vYVdaeE5Ub2s5YWZydWMyTks5b1ZlYXk0WEh3V0RmV2tFZDFzYkNvRTEzRG9Iek9PbTU0Z01RVFF2dS1oaDR0UjdnbklRbXVIR3lJd3RoajE5c01GSjBFYzFvYXNLdHV1eHFsLVVnUkRkR0pXY3pIS0VDdGRIRWg2cHVxZ3B4RnBfSnNlVnpYUDJCMHVWQkE?oc=5",
      "source": "Canton Repository",
      "domain": "cantonrep.com",
      "published": "2026-10-02T14:31:00.000Z",
      "category": "Data Breaches"
    }
  ]
};
